import { describe, it, expect } from "vitest";
import { matchIntent } from "@/lib/assistant/intent-matcher";
import { normalizeUtterance } from "@/lib/assistant/normalize";
import { INTENTS } from "@/lib/assistant/intents";

function resolveIntentId(utterance: string): string {
  const { normalized } = normalizeUtterance(utterance);
  const result = matchIntent(normalized, INTENTS);
  if (result.kind === "match") return result.intent.id;
  if (result.kind === "ambiguous") {
    return `ambiguous:${result.candidates.map((c) => c.id).sort().join("|")}`;
  }
  return "none";
}

const UTTERANCES: [string, string][] = [
  ["how much profit did we make", "profit_summary"],
  ["how much gross profit did we make on 2026-09-01", "profit_summary"],
  ["net profit this month", "profit_summary"],
  ["what was our profit margin last month", "profit_summary"],
  ["show me the profit and loss", "profit_summary"],

  ["what did i sell today", "my_sales_today"],
  ["my sales today", "my_sales_today"],
  ["how much have i sold today", "my_sales_today"],

  ["total sales yesterday", "sales_summary"],
  ["how many sales today", "sales_summary"],
  ["sales for 01/09/2026", "sales_summary"],
  ["sales on 2026-09-01", "sales_summary"],
  ["total sales from 2026-09-01 to 2026-09-15", "sales_summary"],

  ["which products are running out", "inventory_status"],
  ["what is low on stock", "inventory_status"],
  ["show expired items", "inventory_status"],
  ["anything expiring soon", "inventory_status"],
  ["inventory status", "inventory_status"],

  ["do we have panadol", "product_stock"],
  ["how much paracetamol is left", "product_stock"],
  ["how many paracetamol do we have", "product_stock"],
  ["is amoxicillin in stock", "product_stock"],
  ["stock of ibuprofen", "product_stock"],

  ["create a new product", "navigate_add_product"],
  ["add new item to catalog", "navigate_add_product"],
  ["how do i add a product", "navigate_add_product"],

  ["how to sell something", "navigate_make_sale"],
  ["start a new sale", "navigate_make_sale"],
  ["ring up a customer", "navigate_make_sale"],
  ["how do i make a sale", "navigate_make_sale"],

  ["fix a stock count", "navigate_adjust_stock"],
  ["how do i adjust stock", "navigate_adjust_stock"],

  ["export my data", "navigate_backup_data"],
  ["how do i back up my data", "navigate_backup_data"],

  ["order from supplier", "navigate_create_purchase_order"],
  ["create a purchase order", "navigate_create_purchase_order"],
  ["procurement", "navigate_create_purchase_order"],
  ["procurements?", "navigate_create_purchase_order"],

  ["where are the reports", "navigate_view_reports"],
  ["how do i view reports", "navigate_view_reports"],

  ["settings", "navigate_settings"],
  ["settings?", "navigate_settings"],
  ["go to settings", "navigate_settings"],

  ["how do i start a stock audit", "navigate_start_audit"],
  ["how do i record an expense", "navigate_record_expense"],
  ["add a new customer", "navigate_add_customer"],
  ["where do i add staff", "navigate_add_staff"],
  ["how do i run daily close", "navigate_daily_close"],
  ["change the receipt footer", "navigate_receipt_settings"],
  ["how do i switch account", "navigate_switch_account"],

  ["what are my sales today", "my_sales_today"],
  ["how many sales did we do today", "sales_summary"],
  ["show me today's sales", "sales_summary"],
  ["how many transactions yesterday", "sales_summary"],
  ["how much money did we make today", "sales_summary"],
  ["gross profit last month", "profit_summary"],
  ["what is our margin", "profit_summary"],
  ["revenue today", "profit_summary"],
  ["what products are out of stock", "inventory_status"],
  ["which items expire soon", "inventory_status"],
  ["restore my data", "navigate_backup_data"],
  ["reorder from a supplier", "navigate_create_purchase_order"],
  ["open the reports page", "navigate_view_reports"],
  ["i want to sell a product", "navigate_make_sale"],
  ["where is the pos", "navigate_make_sale"],
  ["count stock", "navigate_start_audit"],
  ["stocktake", "navigate_start_audit"],
  ["new cashier", "navigate_add_staff"],
  ["log expense", "navigate_record_expense"],
  ["add customer", "navigate_add_customer"],
  ["customers?", "navigate_add_customer"],
  ["staff", "navigate_add_staff"],
  ["expenses?", "navigate_record_expense"],
  ["audit", "navigate_start_audit"],
  ["audits?", "navigate_start_audit"],

  ["how are we doing on profit this month", "profit_summary"],
  ["did we make a profit today", "profit_summary"],
  ["are we profitable", "profit_summary"],
  ["whats our profit for last month", "profit_summary"],
  ["profit yesterday", "profit_summary"],
  ["how much profit today pls", "profit_summary"],
  ["hey can you tell me the profit margin", "profit_summary"],
  ["whats the p and l for this month", "profit_summary"],
  ["pnl this month", "profit_summary"],
  ["net income this month", "profit_summary"],
  ["earnings this month", "profit_summary"],
  ["how much money did we make after expenses", "profit_summary"],
  ["show me revenue for this month", "profit_summary"],
  ["whats our revenue", "profit_summary"],
  ["profitt this month", "profit_summary"],
  ["cost of goods sold this month", "profit_summary"],
  ["cogs today", "profit_summary"],
  ["how much did we spend on expenses this month", "profit_summary"],
  ["total expenses this month", "profit_summary"],
  ["how much is our gross margin", "profit_summary"],
  ["am i making a profit", "profit_summary"],
  ["bottom line this month", "profit_summary"],
  ["what have i sold so far", "my_sales_today"],
  ["how am i doing today", "my_sales_today"],
  ["how many sales have i made today", "my_sales_today"],
  ["how much have i made today", "my_sales_today"],
  ["how much did i make today", "my_sales_today"],
  ["whats my total for today", "my_sales_today"],
  ["my takings today", "my_sales_today"],
  ["how many customers have i served today", "my_sales_today"],
  ["did i sell anything today", "my_sales_today"],
  ["how much money have i made", "my_sales_today"],
  ["whats my sales figure", "my_sales_today"],
  ["tell me my sales", "my_sales_today"],
  ["how many sales did i do today", "my_sales_today"],
  ["my sales", "my_sales_today"],
  ["my sales for today", "my_sales_today"],
  ["show me the sales report for today", "sales_summary"],
  ["i want to know sales for today", "sales_summary"],
  ["how many sales did we make today", "sales_summary"],
  ["expired stock", "inventory_status"],
  ["stock levels", "inventory_status"],
  ["low stock", "inventory_status"],
  ["do we sell panadol", "product_stock"],
  ["how do i reorder stock", "navigate_create_purchase_order"],
  ["what needs reordering", "inventory_status"],
  ["how are we doing today", "sales_summary"],
  ["hows business today", "sales_summary"],
  ["how did we do yesterday", "sales_summary"],
  ["how was business yesterday", "sales_summary"],
  ["sales today", "sales_summary"],
  ["sales yesterday", "sales_summary"],
  ["what were sales like today", "sales_summary"],
  ["how much sales today", "sales_summary"],
  ["how much in sales did we do yesterday", "sales_summary"],
  ["how many customers did we serve today", "sales_summary"],
  ["number of sales today", "sales_summary"],
  ["how many receipts today", "sales_summary"],
  ["whats the sales figure for yesterday", "sales_summary"],
  ["give me the sales for today", "sales_summary"],
  ["how much money came in today", "sales_summary"],
  ["daily sales", "sales_summary"],
  ["todays takings", "sales_summary"],
  ["cash sales today", "sales_summary"],
  ["what did we sell today", "sales_summary"],
  ["how much did we earn today", "sales_summary"],
  ["how much did the store make yesterday", "sales_summary"],
  ["transactions today", "sales_summary"],
  ["how many sales did we make last month", "sales_summary"],
  ["hey can you tell me the total sales for today please", "sales_summary"],
  ["i want to know how many sales we had today", "sales_summary"],
  ["how much did we sell on 15/09/2026", "sales_summary"],
  ["sales report for today", "sales_summary"],
  ["how many sales", "sales_summary"],
  ["how many panadol left", "product_stock"],
  ["check stock for amoxicillin", "product_stock"],
  ["qty of ibuprofen", "product_stock"],
  ["quantity of ibuprofen", "product_stock"],
  ["do we still have vitamin c", "product_stock"],
  ["have we got panadol", "product_stock"],
  ["is there any amoxil", "product_stock"],
  ["got any paracetamol", "product_stock"],
  ["we have panadol", "product_stock"],
  ["is panadol available", "product_stock"],
  ["how many units of amoxicillin", "product_stock"],
  ["how many amoxicillin are there", "product_stock"],
  ["amoxicillin in stock", "product_stock"],
  ["stock level of paracetamol", "product_stock"],
  ["whats the stock on ibuprofen", "product_stock"],
  ["how much ibuprofen do we have left", "product_stock"],
  ["can u check if we have amoxil", "product_stock"],
  ["how many paracetmol do we have", "product_stock"],
  ["hw many panadol do we have", "product_stock"],
  ["how much panadol extra is remaining", "product_stock"],
  ["is there flagyl in stock", "product_stock"],
  ["do we have panadol in stock", "product_stock"],
  ["paracetamol stock", "product_stock"],
  ["we good on stock", "inventory_status"],
  ["whats running low", "inventory_status"],
  ["what needs restocking", "inventory_status"],
  ["what should i reorder", "inventory_status"],
  ["what expires this month", "inventory_status"],
  ["expiry check", "inventory_status"],
  ["any expired drugs on the shelf", "inventory_status"],
  ["short dated stock", "inventory_status"],
  ["how is our inventory looking", "inventory_status"],
  ["stock check", "inventory_status"],
  ["do we have anything low", "inventory_status"],
  ["what items are below reorder level", "inventory_status"],
  ["which drugs are finishing", "inventory_status"],
  ["what has finished", "inventory_status"],
  ["whats our stock worth", "inventory_status"],
  ["how much stock do we have", "inventory_status"],
  ["what do we need to order", "inventory_status"],
  ["inventory report", "inventory_status"],
  ["stock situation", "inventory_status"],
  ["anything running out", "inventory_status"],
  ["what's about to expire", "inventory_status"],
  ["how do i charge a customer", "navigate_make_sale"],
  ["how to checkout", "navigate_make_sale"],
  ["i need to sell paracetamol", "navigate_make_sale"],
  ["where do i make sales", "navigate_make_sale"],
  ["open the pos", "navigate_make_sale"],
  ["take me to the pos", "navigate_make_sale"],
  ["how do i take payment", "navigate_make_sale"],
  ["how do i scan a product", "navigate_make_sale"],
  ["how do i sell", "navigate_make_sale"],
  ["point of sale", "navigate_make_sale"],
  ["how do i add a new drug to the system", "navigate_add_product"],
  ["register a new product", "navigate_add_product"],
  ["i want to add something to the catalog", "navigate_add_product"],
  ["how do i put a new item in", "navigate_add_product"],
  ["add a medicine", "navigate_add_product"],
  ["the stock count is wrong", "navigate_adjust_stock"],
  ["how do i correct a quantity", "navigate_adjust_stock"],
  ["stock is showing the wrong number", "navigate_adjust_stock"],
  ["how do i reduce stock for damaged items", "navigate_adjust_stock"],
  ["how do i write off expired stock", "navigate_adjust_stock"],
  ["how do i change the stock quantity", "navigate_adjust_stock"],
  ["how do i do a stock count", "navigate_start_audit"],
  ["i want to count my inventory", "navigate_start_audit"],
  ["physical stock count", "navigate_start_audit"],
  ["stock taking", "navigate_start_audit"],
  ["inventory audit", "navigate_start_audit"],
  ["start an audit", "navigate_start_audit"],
  ["how do i enter an expense", "navigate_record_expense"],
  ["i paid for fuel where do i put it", "navigate_record_expense"],
  ["where do i record what i spent", "navigate_record_expense"],
  ["add an expence", "navigate_record_expense"],
  ["track expenses", "navigate_record_expense"],
  ["new expense", "navigate_record_expense"],
  ["how do i register a customer", "navigate_add_customer"],
  ["save a client", "navigate_add_customer"],
  ["where do i put customer details", "navigate_add_customer"],
  ["new patient", "navigate_add_customer"],
  ["create customer", "navigate_add_customer"],
  ["how do i order stock from my supplier", "navigate_create_purchase_order"],
  ["i need to buy more stock", "navigate_create_purchase_order"],
  ["place an order with a supplier", "navigate_create_purchase_order"],
  ["how do i restock", "navigate_create_purchase_order"],
  ["procurement", "navigate_create_purchase_order"],
  ["raise a po", "navigate_create_purchase_order"],
  ["how do i order from my vendor", "navigate_create_purchase_order"],
  ["reorder from supplier", "navigate_create_purchase_order"],
  ["how do i close for the day", "navigate_daily_close"],
  ["eod report", "navigate_daily_close"],
  ["cash up", "navigate_daily_close"],
  ["end the day", "navigate_daily_close"],
  ["closing the shop", "navigate_daily_close"],
  ["close the register", "navigate_daily_close"],
  ["show me the reports", "navigate_view_reports"],
  ["i want to see reports", "navigate_view_reports"],
  ["reports", "navigate_view_reports"],
  ["how do i generate a report", "navigate_view_reports"],
  ["where can i see the sales report", "navigate_view_reports"],
  ["pull up reports", "navigate_view_reports"],
  ["how do i add a user", "navigate_add_staff"],
  ["create a login for my staff", "navigate_add_staff"],
  ["add a worker", "navigate_add_staff"],
  ["reset a staff pin", "navigate_add_staff"],
  ["how do i change permissions for staff", "navigate_add_staff"],
  ["new user", "navigate_add_staff"],
  ["add employee", "navigate_add_staff"],
  ["how do i change the receipt", "navigate_receipt_settings"],
  ["put my logo on the receipt", "navigate_receipt_settings"],
  ["add my phone number to receipts", "navigate_receipt_settings"],
  ["receipt header", "navigate_receipt_settings"],
  ["customize receipts", "navigate_receipt_settings"],
  ["how do i backup", "navigate_backup_data"],
  ["download my data", "navigate_backup_data"],
  ["restore from backup", "navigate_backup_data"],
  ["i lost my data", "navigate_backup_data"],
  ["move my data to a new laptop", "navigate_backup_data"],
  ["backup", "navigate_backup_data"],
  ["import data", "navigate_backup_data"],
  ["how do i log out", "navigate_switch_account"],
  ["change account", "navigate_switch_account"],
  ["switch user", "navigate_switch_account"],
  ["log in as another cashier", "navigate_switch_account"],
  ["sign in as someone else", "navigate_switch_account"],
  ["switch account", "navigate_switch_account"],
];

describe("assistant utterance coverage (the plan's post-data-tools sweep, pinned)", () => {
  it.each(UTTERANCES)("routes %j to %s", (utterance, expectedId) => {
    expect(resolveIntentId(utterance)).toBe(expectedId);
  });

  it("does not route a refund question to a sales or profit data tool", () => {
    const resolved = resolveIntentId("how do i refund a sale");
    expect(["sales_summary", "my_sales_today", "profit_summary"]).not.toContain(resolved);
  });

  it.each([
    ["what is the weather today"],
    ["hello"],
    ["thanks"],
    ["how many products do we have"],
    ["how do i add stock"],
    ["receipt not printing"],
    ["whats selling well"],
    ["best sellers this week"],
    ["how much does paracetamol cost"],
    ["price of paracetamol"],
    ["who sold the most today"],
    ["how much do we owe suppliers"],
    ["what can you do"],
    ["how do i return an item"],
    ["the customer paid for it already"],
    ["restore the app"],
    ["set reorder level for panadol"],
    ["my subscription expired"],
  ])(
    "still returns none for %j",
    (utterance) => {
      expect(resolveIntentId(utterance)).toBe("none");
    },
  );
});
