/**
 * Helper for PDF Reporting Export
 */

export interface PLReportData {
  period: string;
  revenue: number;
  cogs: number;
  expenses: number;
  netProfit: number;
  expenseBreakdown: { category: string; amount: number }[];
}

export const exportPLReportToPDF = (data: PLReportData, storeName: string) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const html = `
    <html>
      <head>
        <title>P&L Report - ${data.period}</title>
        <style>
          body {
            font-family: 'Inter', sans-serif;
            color: #1a1a1a;
            padding: 40px;
            max-width: 800px;
            margin: 0 auto;
          }
          .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 2px solid #f0f0f0;
            padding-bottom: 20px;
          }
          .header h1 { margin: 0; font-size: 24pt; color: #111; }
          .header p { margin: 5px 0 0; color: #666; }
          
          .summary-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            margin-bottom: 40px;
          }
          .card {
            padding: 20px;
            background: #f9f9f9;
            border-radius: 12px;
          }
          .card label { font-size: 10pt; color: #666; font-weight: bold; text-transform: uppercase; }
          .card value { display: block; font-size: 18pt; font-weight: bold; margin-top: 5px; }
          
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th { text-align: left; padding: 12px; border-bottom: 1px solid #ddd; font-size: 10pt; color: #666; }
          td { padding: 12px; border-bottom: 1px solid #eee; font-size: 11pt; }
          
          .footer {
            margin-top: 60px;
            text-align: center;
            font-size: 9pt;
            color: #999;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${storeName}</h1>
          <p>Profit & Loss Statement - ${data.period}</p>
        </div>

        <div class="summary-grid">
          <div class="card">
            <label>Total Revenue</label>
            <value>NGN ${data.revenue.toLocaleString()}</value>
          </div>
          <div class="card">
            <label>Net Profit</label>
            <value style="color: ${data.netProfit >= 0 ? '#10b981' : '#ef4444'}">
                NGN ${data.netProfit.toLocaleString()}
            </value>
          </div>
        </div>

        <h3>Financial Breakdown</h3>
        <table>
          <thead>
            <tr>
              <th>Description</th>
              <th style="text-align: right;">Amount</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Total Sales (Revenue)</td>
              <td style="text-align: right;">NGN ${data.revenue.toLocaleString()}</td>
            </tr>
            <tr>
              <td>Cost of Goods Sold (COGS)</td>
              <td style="text-align: right;">(NGN ${data.cogs.toLocaleString()})</td>
            </tr>
            <tr style="font-weight: bold; background: #fafafa;">
              <td>Gross Profit</td>
              <td style="text-align: right;">NGN ${(data.revenue - data.cogs).toLocaleString()}</td>
            </tr>
            <tr>
              <td>Operating Expenses</td>
              <td style="text-align: right;">(NGN ${data.expenses.toLocaleString()})</td>
            </tr>
            <tr style="font-weight: bold; font-size: 14pt; border-top: 2px solid #111;">
              <td>Net Profit / Loss</td>
              <td style="text-align: right;">NGN ${data.netProfit.toLocaleString()}</td>
            </tr>
          </tbody>
        </table>

        <h3>Expense Breakdown</h3>
        <table>
          <thead>
            <tr>
              <th>Category</th>
              <th style="text-align: right;">Amount</th>
            </tr>
          </thead>
          <tbody>
            ${data.expenseBreakdown.map(exp => `
              <tr>
                <td>${exp.category}</td>
                <td style="text-align: right;">NGN ${exp.amount.toLocaleString()}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <div class="footer">
          Generated by DumosRx Professional on ${new Date().toLocaleDateString()}
        </div>

        <script>
          window.onload = () => {
            window.print();
            window.onafterprint = () => window.close();
          };
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
};
