<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Customers
        Schema::create('customers', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('first_name');
            $table->string('last_name');
            $table->string('email')->nullable();
            $table->string('phone')->nullable();
            $table->text('address')->nullable();
            $table->date('date_of_birth')->nullable();
            $table->string('gender')->nullable();
            $table->text('allergies')->nullable(); // JSON or Text
            $table->text('medical_conditions')->nullable();
            $table->integer('loyalty_points')->default(0);
            $table->timestamps();
        });

        // Prescriptions
        Schema::create('prescriptions', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('prescription_number')->unique(); // RX... generated by App
            $table->foreignUuid('customer_id')->nullable()->constrained()->nullOnDelete();
            $table->string('doctor_name')->nullable();
            $table->string('hospital_name')->nullable();
            $table->date('prescription_date');
            $table->text('diagnosis')->nullable();
            $table->text('notes')->nullable();
            $table->enum('status', ['pending', 'dispensed', 'substituted', 'unavailable'])->default('pending');
            $table->foreignUuid('substituted_medicine_id')->nullable()->constrained('medicines')->nullOnDelete();
            $table->text('substitution_reason')->nullable();
            $table->timestamps();
        });

        // Prescription Items
        Schema::create('prescription_items', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->foreignUuid('prescription_id')->constrained()->cascadeOnDelete();
            $table->foreignUuid('medicine_id')->constrained()->cascadeOnDelete();
            $table->string('dosage')->nullable(); // e.g. "1 tab twice daily"
            $table->integer('quantity_prescribed');
            $table->integer('quantity_dispensed')->default(0);
            $table->enum('status', ['pending', 'dispensed', 'substituted', 'unavailable'])->default('pending');
            $table->timestamps();
        });

        // Sales
        Schema::create('sales', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('transaction_number')->unique(); // TXN... generated by App
            $table->foreignUuid('customer_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignUuid('cashier_id')->constrained('users'); // Validated by backend
            $table->foreignUuid('prescription_id')->nullable()->constrained()->nullOnDelete();
            
            // Financials
            $table->decimal('subtotal', 10, 2)->default(0.00);
            $table->decimal('discount_amount', 10, 2)->default(0.00);
            $table->decimal('discount_percentage', 5, 2)->default(0.00);
            $table->decimal('tax_amount', 10, 2)->default(0.00);
            $table->decimal('tax_percentage', 5, 2)->default(7.5);
            $table->decimal('total_amount', 10, 2);
            
            // Payment
            $table->enum('payment_method', ['cash', 'card', 'transfer', 'mobile_money', 'insurance']);
            $table->enum('payment_status', ['pending', 'completed', 'failed', 'refunded'])->default('completed');
            $table->decimal('amount_paid', 10, 2);
            $table->decimal('change_given', 10, 2)->default(0.00);
            
            // Loyalty
            $table->integer('points_earned')->default(0);
            $table->integer('points_redeemed')->default(0);
            
            $table->timestamp('transaction_date')->useCurrent();
            $table->text('notes')->nullable();
            $table->boolean('receipt_printed')->default(false);
            $table->timestamps();
        });

        // Sale Items
        Schema::create('sale_items', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->foreignUuid('sale_id')->constrained()->cascadeOnDelete();
            $table->foreignUuid('medicine_id')->constrained();
            $table->foreignUuid('inventory_id')->constrained(); // Link to specific batch
            $table->integer('quantity');
            $table->decimal('unit_price', 10, 2);
            $table->decimal('discount_amount', 10, 2)->default(0.00);
            $table->decimal('total_price', 10, 2);
            $table->decimal('cost_price', 10, 2); // Snapshot ensuring profit calculation doesn't change
            // Profit is calculated in code or generated column if DB supports it. 
            // Postgres had GEN ALWAYS AS. MySQL 5.7+ supports generated columns but simpler to keep generic for now.
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('sale_items');
        Schema::dropIfExists('sales');
        Schema::dropIfExists('prescription_items');
        Schema::dropIfExists('prescriptions');
        Schema::dropIfExists('customers');
    }
};
