export interface HelpTopic {
  id: string;
  title: string;
  href: string | null;
  steps: string[];
  keywords: string[];
  phrases: RegExp[];
  requiredPermission?: string;
}

export const HELP_TOPICS: HelpTopic[] = [
  {
    id: "make_sale",
    title: "Make a sale",
    href: "/pos",
    steps: ["Open POS", "Search or scan the product", "Add it to the cart", "Tap Charge and choose a payment method"],
    keywords: ["sale", "sell", "checkout", "pos", "ring up"],
    phrases: [
      /\bmake (a |new |some |the )?sales?\b/,
      /\bprocess a sale\b/,
      /\bhow (do|to|can) (i |we )?(make|process|do|start) a sale\b/,
      /\bhow (do|to|can) (i |we )?sell\b/,
      /\bsell (a |an |the |some )?(product|item|drug|medicine|something)\b/,
      /\bstart (a |an |the )?(new )?sale\b/,
      /\bring up\b/,
      /\b(need|want|would like|wanna|trying|going|about) to (sell|make a sale|ring up|checkout|check out)\b/,
      /\bcharge (a |the )?(customer|client|patient|someone)\b/,
      /\bcheck ?out\b/,
      /\bpoint of sale\b/,
      /\b(open|go to|take me to|show me|launch|start|where is|wheres|find) (the |my )?(pos|point of sale|till|checkout|sales screen)\b/,
      /\b(take|accept|collect|receive) (a |the )?payment\b/,
      /\bscan (a |the |an )?(product|item|barcode|drug)\b/,
    ],
    requiredPermission: "process_sales",
  },
  {
    id: "add_product",
    title: "Add a product",
    href: "/inventory/catalog?action=add",
    steps: ["Go to Inventory > Catalog", "Tap Add Product", "Fill in the product details and save"],
    keywords: ["add product", "new product", "create product", "add item", "new item", "catalog", "catalogue"],
    phrases: [
      /\b(add|create|register|enter|input|put|upload|set up|setup|make|new) (a |an |the |new |a new |another )?(product|item|drug|medicine|medication|sku|catalog item)\b/,
      /\badd .*\b(to|into|in) (the |my |our )?(catalog|catalogue|system)\b/,
    ],
    requiredPermission: "manage_products",
  },
  {
    id: "adjust_stock",
    title: "Adjust stock",
    href: "/inventory/adjustments?action=create",
    steps: ["Go to Inventory > Adjustments", "Tap New Adjustment", "Select the product and enter the correction"],
    keywords: ["adjust stock", "correct stock", "stock adjustment", "fix stock"],
    phrases: [
      /\badjust stock\b/,
      /\bcorrect stock\b/,
      /\bstock adjustment\b/,
      /\bfix (a |an |the )?stock\b/,
      /\b(fix|correct) (a |an |the )?(stock )?count\b/,
      /\b(count|stock|quantity|qty|number|figure) (is|s|looks|shows|showing) (wrong|incorrect|off|not right|not correct)\b/,
      /\b(showing|shows) (the |a )?wrong\b/,
      /\b(fix|correct|change|update|edit|amend|reduce|increase|adjust) (a |an |the |my |our )?(stock |product |item )?(quantity|qty|count|stock level|stock|number|numbers|balance|figures?)\b/,
      /\bwrite ?off\b/,
      /\b(damaged|broken|spoilt|spoiled|wastage|breakage|shrinkage|stolen|missing|expired|expiring) (stock|items?|goods|products|drugs|units)\b/,
    ],
    requiredPermission: "adjust_stock_counts",
  },
  {
    id: "start_audit",
    title: "Start a stock audit",
    href: "/inventory/audits",
    steps: ["Go to Inventory > Audits", "Tap Start Audit", "Count and confirm each product"],
    keywords: ["stock audit", "stocktake", "count stock"],
    phrases: [
      /\bstock audit\b/,
      /\binventory audit\b/,
      /\bstock ?take\b/,
      /\bstock ?taking\b/,
      /\bcount (my |the |our |all )?(stock|inventory|items|products|shelf|shelves|drugs)\b/,
      /\b(do|start|run|begin|perform|carry out|conduct|new|open) (a |an |the |my |our )?(stock ?count|stock ?take|audit|inventory count|physical count)\b/,
      /\bphysical (stock )?(count|inventory|check)\b/,
    ],
    requiredPermission: "perform_stock_audit",
  },
  {
    id: "record_expense",
    title: "Record an expense",
    href: "/expenses?action=add",
    steps: ["Go to Expenses", "Tap Add Expense", "Enter the amount, category, and date"],
    keywords: ["record expense", "add expense", "log expense"],
    phrases: [
      /\b(record|add|log|enter|input|put|capture|track|register|create|new|save|note|post) (an |a |the |my |our |some |todays )?(expenses?|expence|expences|spending|bill|bills|outgoings?)\b/,
      /\bwhat i spent\b/,
      /\bi (paid|payed) for\b/,
      /\bexpenses? (page|screen|tab|section)\b/,
    ],
    requiredPermission: "record_expenses",
  },
  {
    id: "add_customer",
    title: "Add a customer",
    href: "/customers?action=add",
    steps: ["Go to Customers", "Tap Add Customer", "Fill in their details and save"],
    keywords: ["add customer", "new customer"],
    phrases: [
      /\b(add|register|create|save|enter|new|input|make|set up|setup|onboard) (a |an |the |new |a new |another )?(customer|client|patient|buyer|shopper)s?\b/,
      /\bcustomer (details|info|information|profile|record|list)\b/,
      /\b(customers|clients|patients) (page|screen|tab|list)\b/,
    ],
    requiredPermission: "manage_customers",
  },
  {
    id: "create_purchase_order",
    title: "Create a purchase order",
    href: "/procurement/new",
    steps: ["Go to Procurement", "Tap New Purchase Order", "Select a supplier and add line items"],
    keywords: ["purchase order", "reorder from supplier", "procurement", "supplier", "vendor"],
    phrases: [
      /\bpurchase order\b/,
      /\b(re)?order .{0,30}\b(from|with|to) (a |an |the |my |our )?(supplier|vendor|distributor|wholesaler|manufacturer)\b/,
      /\b(supplier|vendor) order\b/,
      /\b(buy|purchase|order|reorder|get) (more |new |some |additional )?(stock|goods|products|inventory|supplies|drugs|items)\b/,
      /\brestock\b/,
      /\b(raise|create|make|place|new|open|start|send) (a |an |the )?(po|purchase order|requisition)\b/,
      /\bplace (an |a )?order\b/,
      /\bprocurement\b/,
    ],
    requiredPermission: "manage_purchase_orders",
  },
  {
    id: "daily_close",
    title: "Run daily close",
    href: "/reports?tab=daily_close",
    steps: ["Go to Reports > Daily Close", "Review the summary", "Confirm to close the day"],
    keywords: ["daily close", "close the day", "end of day"],
    phrases: [
      /\bdaily close\b/,
      /\bclos(e|ing) (up |out |off )?(for |of )?(the |today|tonight|this )?(day|shop|store|register|till|business|shift|books)\b/,
      /\bend[- ]of[- ]day\b/,
      /\beod\b/,
      /\bday end\b/,
      /\bend (the |my |of the |of my )?(day|shift|trading)\b/,
      /\bcash(ing)? ?up\b/,
      /\breconcile\b/,
      /\bclose out\b/,
      /\bz report\b/,
    ],
    requiredPermission: "run_daily_close",
  },
  {
    id: "view_reports",
    title: "View reports",
    href: "/reports",
    steps: ["Go to Reports from the sidebar", "Choose a report tab (Sales, Finance, Daily Close)"],
    keywords: ["view reports", "see reports", "reports page", "reports", "report"],
    phrases: [
      new RegExp(
        "^(?!.*\\b(today|yesterday|this month|last month|\\d{2}/\\d{2}/\\d{4}|\\d{4}-\\d{2}-\\d{2})\\b).*\\b(view|see|show|open|get|pull up|check|find|look at|go to|take me to|generate|run|create|make|print|export|download|access|display) (me )?(the |my |all |a |some |our )?(sales |finance |financial |stock |inventory |profit |expense |daily )?reports?\\b",
      ),
      /\bwhere (can|do|would|should|could) i .*\breports?\b/,
      /^reports?$/,
      /\breports? (page|screen|tab|section|centre|center)\b/,
      /\bwhere (are|is) (the |my )?reports?\b/,
    ],
    requiredPermission: "view_reports",
  },
  {
    id: "add_staff",
    title: "Add a staff member",
    href: "/settings/staff",
    steps: ["Go to Settings > Staff", "Tap Add Staff", "Set their name, PIN, and permission group"],
    keywords: ["add staff", "new staff", "add employee", "add cashier"],
    phrases: [
      /\b(add|create|register|invite|set up|setup|onboard|make|new) (a |an |the |new |a new )?(staff|employee|cashier|user|worker|member|team member|salesperson|sales person|attendant|pharmacist|account for|login for|login)\b/,
      /\b(set|give|change|reset|forgot|forgotten) (a |the |their |my |his |her |someones )?(staff |cashier |user )?pin\b/,
      /\bpermissions?\b/,
      /\b(staff|employee|user|cashier) (pin|role|roles|permission|permissions|access|account|accounts|list|page|management)\b/,
      /\b(manage|remove|delete|deactivate|disable) (a |an |the )?(staff|employee|cashier|user)\b/,
    ],
    requiredPermission: "manage_staff",
  },
  {
    id: "receipt_settings",
    title: "Change receipt settings",
    href: "/settings/receipt-settings",
    steps: ["Go to Settings > Receipt Settings", "Edit the receipt header/footer text or logo"],
    keywords: ["receipt settings", "receipt logo", "receipt footer"],
    phrases: [
      /\breceipt (settings?|logo|footer|header|text|layout|format|design|template|message|details|setup)\b/,
      /\b(change|edit|update|customi[sz]e|set up|setup|configure|modify|design|fix) (the |my |our )?receipts?\b/,
      /\b(logo|header|footer|phone number|address|message|name|slogan|thank you) (on|to|for|from) (the |my |our )?receipts?\b/,
      /\b(add|put|show|remove|include|display) .*\b(on|to|from|in) (the |my |our )?receipts?\b/,
    ],
    requiredPermission: "manage_store_settings",
  },
  {
    id: "backup_data",
    title: "Back up or restore data",
    href: "/settings/data",
    steps: ["Go to Settings > Data", "Choose Backup or Restore"],
    keywords: ["backup data", "restore data", "export data", "backup", "restore"],
    phrases: [
      /\bback ?ups?\b/,
      /\brestore (my |the |all |our |a )?(data|backup|database|from)\b/,
      /\b(export|download|save|copy|import|upload|transfer|move|migrate|sync) (my |the |all |our |all my |all the )?(data|database|records|everything|files|db|information)\b/,
      /\blost (my |the |all |our |all my )?(data|records|sales|database|everything)\b/,
      /\b(move|transfer|migrate|copy) .*\b(new|another|other) (phone|computer|laptop|device|pc|tablet|machine)\b/,
      /\bdata (page|screen|tab|settings|backup|export|restore)\b/,
    ],
    requiredPermission: "backup_restore_data",
  },
  {
    id: "switch_account",
    title: "Switch account",
    href: null,
    steps: ["Open the account menu (top right / user icon)", "Choose Switch Account", "Or choose Log Out to sign out completely"],
    keywords: ["switch account", "change user", "log in as someone else"],
    phrases: [
      /\bswitch (the )?(account|accounts|user|users|cashier|login|profile|staff)\b/,
      /\bchange (the )?(account|user|users|cashier|login|profile|who is logged in)\b/,
      /\b(log|sign) ?(in|on) as\b/,
      /\banother (user|account|cashier|person|staff)\b/,
      /\b(log|sign) ?(out|off)\b/,
      /\bsomeone else\b/,
    ],
  },
];
