/* eslint-disable max-lines */
export const FORM_SUGGESTIONS = {
  "pharmacy": {
    "names": [
      "Advil",
      "Albenda",
      "Albendazole",
      "Amatem",
      "Amatem Softgel",
      "Amlo",
      "Amlodipine",
      "Amoxicillin",
      "Ampicillin",
      "Ampiclox",
      "Ampliclox",
      "Andrews Liver Salt",
      "Artemether/Lumefantrine",
      "Artesun",
      "Artesunate",
      "Astyfer",
      "Astymin",
      "Atorvastatin",
      "Augmentin",
      "Augmentin 1g",
      "Augmentin 625mg",
      "Avomine",
      "Azithro",
      "Azithromycin",
      "B-Complex",
      "Bactoban",
      "Beecham Ampiclox",
      "Blood Tonic",
      "Buscopan",
      "Canesten",
      "Cataflam",
      "Ceftriaxone",
      "Cefuroxime",
      "Cetirizine",
      "Cevit",
      "Chemiron",
      "Ciproflox",
      "Ciprofloxacin",
      "Ciprotab",
      "Claritin",
      "Clotrimazole",
      "Cloxacillin",
      "Coartem",
      "Coartem 80/480",
      "Cod Liver Oil",
      "Codeine",
      "Cozaar",
      "Dettol Antiseptic",
      "Dexa",
      "Dexamethasone",
      "Diabinese",
      "Diclo Sodium",
      "Diclofenac",
      "Durex",
      "Emzor Paracetamol",
      "Emzor Vitamin C",
      "Feldene",
      "Feroglobin",
      "Fersolate",
      "Fiesta",
      "Flagyl",
      "Folic Acid",
      "Funbact-A",
      "Gaviscon",
      "Gentamicin",
      "Gestid",
      "Glucophage",
      "Gripe Water",
      "Gvither",
      "HCTZ",
      "Humulin",
      "Hydrite",
      "Hydrochlorothiazide",
      "Hydrogen Peroxide",
      "Hyoscine",
      "Ibu",
      "Ibuprofen",
      "Inhaler",
      "Insulin",
      "K-Y Jelly",
      "L-Artem",
      "Lipitor",
      "Lisinopril",
      "Lofem",
      "Lonart",
      "Lonart DS",
      "Loratadine",
      "Losartan",
      "Losec",
      "Lubricant",
      "Magnesium Trisilicate",
      "Metformin",
      "Methylated Spirit",
      "Metronidazole",
      "Milk of Magnesia",
      "Mist Mag",
      "Mixtard",
      "Neomycin",
      "Nexium",
      "Norvasc",
      "Nurofen",
      "Nystatin",
      "Omega 3",
      "Omeprazole",
      "Oral Rehydration Salt (ORS)",
      "P-Alaxin",
      "Panadol",
      "Panadol Child",
      "Panadol Extra",
      "Paracetamol",
      "Pears Gripe Water",
      "Phenergan",
      "Piccan",
      "Piroxicam",
      "Postinor-2",
      "Prednisolone",
      "Promethazine",
      "Rocephin",
      "Rough Rider",
      "Salbutamol",
      "Savlon",
      "Seven Seas",
      "Skineal",
      "Tramadol",
      "Ventolin",
      "Visine",
      "Vitamin C",
      "Voltaren",
      "Woodwards Gripe Water",
      "Zentel",
      "Zestril",
      "Zinacef",
      "Zinnat",
      "Zithromax",
      "Zyrtec"
    ],
    "generics": [
      "Acetaminophen",
      "Albendazole",
      "Amlodipine",
      "Amoxicillin/Clavulanate",
      "Ampicillin",
      "Artemether/Lumefantrine",
      "Artesunate",
      "Ascorbic Acid",
      "Atenolol",
      "Atorvastatin",
      "Azithromycin",
      "Captopril",
      "Ceftriaxone",
      "Cefuroxime",
      "Cetirizine",
      "Ciprofloxacin",
      "Clarithromycin",
      "Clotrimazole",
      "Cloxacillin",
      "Dexamethasone",
      "Diclofenac Sodium",
      "Doxycycline",
      "Erythromycin",
      "Ferrous Sulphate",
      "Fluconazole",
      "Folic Acid",
      "Furosemide",
      "Glibenclamide",
      "Glimepiride",
      "Griseofulvin",
      "Guanfacine",
      "Hydralazine",
      "Hydrochlorothiazide",
      "Hyoscine Butylbromide",
      "Ibuprofen",
      "Insulin Isophane",
      "Insulin Soluble",
      "Ketoconazole",
      "Levofloxacin",
      "Lisinopril",
      "Loratadine",
      "Losartan",
      "Metformin",
      "Metformin Hydrochloride",
      "Methyldopa",
      "Metronidazole",
      "Multivitamins",
      "Nifedipine",
      "Nystatin",
      "Omeprazole",
      "Piroxicam",
      "Prednisolone",
      "Promethazine",
      "Salbutamol",
      "Simvastatin",
      "Spironolactone",
      "Tetracycline",
      "Vitamin B12"
    ],
    "strengths": [
      "IU",
      "mcg",
      "percentage (%)",
      "units",
      "v/v",
      "w/v",
      "w/w",
      "µg",
      "0.75mg",
      "1.5mg",
      "2.5mg",
      "5mg",
      "5ml",
      "10mg",
      "10ml",
      "15ml",
      "20/120mg",
      "20mg",
      "30mg",
      "40/240mg",
      "40mg",
      "50mg",
      "50ml",
      "60mg",
      "60ml",
      "75mg",
      "80/480mg",
      "80mg",
      "100mg",
      "100ml",
      "125mg",
      "150mg",
      "150ml",
      "160mg",
      "200ml",
      "250/500mg",
      "250mg",
      "250ml",
      "320mg",
      "400mg",
      "450mg",
      "500mg",
      "500ml",
      "600mg",
      "625mg",
      "800mg",
      "900mg",
      "1g",
      "1.2g",
      "1.5g",
      "2g",
      "3g",
      "4g",
      "5g"
    ],
    "categories": [
      "Analgesics",
      "Antacids",
      "Anthelmintics",
      "Anti-diarrheals",
      "Anti-emetics",
      "Antibiotics",
      "Anticonvulsants",
      "Antidepressants",
      "Antidiabetics",
      "Antifungals",
      "Antihistamines",
      "Antihypertensives",
      "Antimalarials",
      "Antiseptics",
      "Antivirals",
      "Baby Care",
      "Cough & Cold",
      "Dermatologicals",
      "Eye/Ear Drops",
      "Family Planning",
      "First Aid",
      "Inhalers & Respiratory",
      "Injectables",
      "Laxatives",
      "Medical Devices",
      "Surgicals",
      "Vitamins & Supplements"
    ],
    "dosageForms": [
      "Caplet",
      "Capsule",
      "Cream",
      "Drops",
      "Elixir",
      "Gel",
      "Infusion",
      "Inhaler",
      "Injection",
      "Liniment",
      "Lotion",
      "Ointment",
      "Patch",
      "Pessary",
      "Powder",
      "Sachet",
      "Softgel",
      "Solution",
      "Spray",
      "Suppository",
      "Suspension",
      "Syrup",
      "Tablet"
    ],
    "manufacturers": [
      "AstraZeneca",
      "Bayer",
      "Bond Chemical",
      "Chi Pharmaceuticals",
      "Cipla",
      "Dana Pharmaceuticals",
      "Drugfield Pharmaceuticals",
      "Emzor Pharmaceuticals",
      "Evans Medical",
      "Fidson Healthcare",
      "Geneith Pharmaceuticals",
      "Getz Pharma",
      "Greenlife Pharmaceuticals",
      "GSK Nigeria",
      "Hovid",
      "Juhel Nigeria",
      "M&B",
      "May & Baker Nigeria",
      "Mecure Industries",
      "MeCure Industries",
      "Micro Labs",
      "Neimeth International",
      "Novartis",
      "Orange Drug",
      "Pfizer Nigeria",
      "Pharma-Deko",
      "Reals Pharma",
      "Roche",
      "Sam Pharmaceutical",
      "Sanofi Nigeria",
      "Shalina Healthcare",
      "SKG Pharma",
      "Sun Pharma (Ranbaxy)",
      "Swiss Pharma (Swipha)",
      "Triveni",
      "Unique Pharma",
      "Vanguard Pharmacy",
      "Zolon Healthcare"
    ]
  },
  "retail": {
    "names": [
      "7Up",
      "Air Wick",
      "Always Sanitary Pad",
      "Amstel Malta",
      "Aquafina",
      "Ariel Detergent",
      "Bigi Drinks",
      "Bournvita",
      "Checkers Custard",
      "Close Up",
      "Coca-Cola",
      "Colgate",
      "Corn Flakes",
      "Cowbell",
      "Cway Water",
      "Dano Milk",
      "Dettol Soap",
      "Devon King's Oil",
      "Dubic Malt",
      "Eva Water",
      "Fanta",
      "Gino Oil",
      "Golden Morn",
      "Harpic",
      "Hypo Bleach",
      "Indomie Chicken",
      "Indomie Noodles",
      "Indomie Onion",
      "Indomie Super Pack",
      "Jik",
      "Johnson's Baby",
      "Joy Soap",
      "Kellogg's Corn Flakes",
      "Knorr",
      "Lady B Custard",
      "Loya Milk",
      "Lux Soap",
      "Macleans",
      "Maggi",
      "Maggi Crayfish",
      "Maggi Star",
      "Malta Guinness",
      "Maltina",
      "Mamador Oil",
      "Milo",
      "Mirinda",
      "Molfix Diapers",
      "MyMy",
      "Omo",
      "Oral B",
      "Pampers",
      "Peak Liquid",
      "Peak Milk",
      "Pears Baby Oil",
      "Pepsi",
      "Premier Cool",
      "Savlon",
      "Sprite",
      "Sunlight Detergent",
      "Three Crowns Milk",
      "Viju Milk"
    ],
    "generics": [],
    "strengths": [
      "Economy",
      "Family Pack",
      "Large",
      "Medium",
      "Sachet",
      "Small",
      "35cl",
      "50cl",
      "60cl",
      "75cl",
      "1L",
      "2L",
      "5L",
      "20L",
      "70g",
      "120g",
      "150g",
      "200g",
      "400g",
      "450g",
      "500g",
      "900g",
      "1kg",
      "2kg",
      "5kg",
      "10kg",
      "25kg",
      "50kg"
    ],
    "categories": [
      "Baby Products",
      "Beverages",
      "Cereals",
      "Cleaning Agents",
      "Dairy",
      "Detergents",
      "Food & Spices",
      "Grains & Pasta",
      "Groceries",
      "Household",
      "Kitchenware",
      "Laundry",
      "Noodles",
      "Oils & Fats",
      "Personal Care",
      "Snacks",
      "Soft Drinks",
      "Stationery",
      "Toiletries",
      "Water"
    ],
    "dosageForms": [],
    "manufacturers": [
      "Beloxxi Industries",
      "BUA Group",
      "Cadbury Nigeria",
      "Chi Limited",
      "Coca-Cola Hellenic",
      "Dangote Group",
      "Dufil Prima Foods",
      "Flour Mills of Nigeria",
      "Guinness Nigeria",
      "Honeywell Flour Mills",
      "Multipro Consumer",
      "Nestle Nigeria",
      "Nigerian Breweries",
      "Ok Foods",
      "Promasidor",
      "PZ Cussons",
      "Tolaram Group",
      "Unilever Nigeria",
      "Yale Foods"
    ]
  },
  "common": {
    "units": [
      "Ampoule",
      "Bag",
      "Bottle",
      "Box",
      "Can",
      "Caplet",
      "Capsule",
      "Card",
      "Carton",
      "Crate",
      "Drum",
      "Jar",
      "Pack",
      "Piece",
      "Roll",
      "Sachet",
      "Spoonful",
      "Tablet",
      "Tin",
      "Tray",
      "Tube",
      "Vial"
    ],
    "locations": [
      "Aba",
      "Abakaliki",
      "Abeokuta",
      "Abiriba",
      "Abor",
      "Abuja",
      "Ado-Ekiti",
      "Afikpo",
      "Agbani",
      "Agbogugu",
      "Aguleri",
      "Akure",
      "Amasiri",
      "Anara",
      "Arochukwu",
      "Asaba",
      "Atani",
      "Awgu",
      "Awka",
      "Bauchi",
      "Bende",
      "Benin City",
      "Birnin Kebbi",
      "Calabar",
      "Damaturu",
      "Dutse",
      "Edda",
      "Ekwulobia",
      "Enugu",
      "Gombe",
      "Gusau",
      "Ibadan",
      "Igboukwu",
      "Ihiala",
      "Ikwo",
      "Ikwuano",
      "Ilorin",
      "Ishiagu",
      "Jalingo",
      "Jos",
      "Kaduna",
      "Kano",
      "Katsina",
      "Lafia",
      "Lagos",
      "Lokoja",
      "Maiduguri",
      "Makurdi",
      "Mbaise",
      "Minna",
      "Nkalagu",
      "Nkpor",
      "Nnewi",
      "Nsukka",
      "Obosi",
      "Ogidi",
      "Oguta",
      "Ohafia",
      "Oji",
      "Oji River",
      "Okigwe",
      "Oko",
      "Okposi",
      "Omoba",
      "Onitsha",
      "Onueke",
      "Oraifite",
      "Orlu",
      "Osogbo",
      "Owerri",
      "Ozubulu",
      "Port Harcourt",
      "Sokoto",
      "Uburu",
      "Udi",
      "Umuahia",
      "Umuleri",
      "Umunze",
      "Umuoji",
      "Uyo",
      "Warri",
      "Yola",
      "Zaria"
    ],
    "states": [
      "Abia State",
      "Adamawa State",
      "Akwa Ibom State",
      "Anambra State",
      "Bauchi State",
      "Bayelsa State",
      "Benue State",
      "Borno State",
      "Cross River State",
      "Delta State",
      "Ebonyi State",
      "Edo State",
      "Ekiti State",
      "Enugu State",
      "FCT - Abuja",
      "Gombe State",
      "Imo State",
      "Jigawa State",
      "Kaduna State",
      "Kano State",
      "Katsina State",
      "Kebbi State",
      "Kogi State",
      "Kwara State",
      "Lagos State",
      "Nasarawa State",
      "Niger State",
      "Ogun State",
      "Ondo State",
      "Osun State",
      "Oyo State",
      "Plateau State",
      "Rivers State",
      "Sokoto State",
      "Taraba State",
      "Yobe State",
      "Zamfara State"
    ]
  }
};