/* eslint-disable max-lines */
export const FORM_SUGGESTIONS = {
  store: {
    names: [
      // Analgesics / pain & fever
      "Advil",
      "Andrews Answer",
      "Cafenol",
      "Cataflam",
      "Diclo Sodium",
      "Diclofenac",
      "Emzor Paracetamol",
      "Feldene",
      "Fem-1",
      "Flexi Rub",
      "Ibu",
      "Ibuprofen",
      "Naproxen",
      "Novalgin",
      "Nurofen",
      "P-Alaxin",
      "Panadol",
      "Panadol Child",
      "Panadol Extra",
      "Paracetamol",
      "Piroxicam",
      "Reme",
      "Tramadol",
      "Voltaren",
      // Antimalarials
      "Amatem",
      "Amatem Softgel",
      "Artemether/Lumefantrine",
      "Artesun",
      "Artesunate",
      "Camosunate",
      "Coartem",
      "Coartem 80/480",
      "Duo-Cotecxin",
      "Fansidar",
      "Green Cap",
      "Jonnys Cool",
      "Lonart",
      "Lonart DS",
      "Lumartem",
      "Malareich",
      "P-Alaxin Forte",
      // Antibiotics
      "Amoxicillin",
      "Amoxil",
      "Ampicillin",
      "Ampiclox",
      "Ampliclox",
      "Augmentin",
      "Augmentin 1g",
      "Augmentin 625mg",
      "Azithro",
      "Azithromycin",
      "Bactrim",
      "Beecham Ampiclox",
      "Ceftriaxone",
      "Cefuroxime",
      "Ciproflox",
      "Ciprofloxacin",
      "Ciprotab",
      "Cloxacillin",
      "Doxycycline",
      "Erythrocin",
      "Floxapen",
      "Gentamicin",
      "Klacid",
      "Neomycin",
      "Norfloxacin",
      "Ofloxacin",
      "Peflacine",
      "Rocephin",
      "Septrin",
      "Tarivid",
      "Vibramycin",
      "Zinacef",
      "Zinnat",
      "Zithromax",
      // Antihistamines / allergy
      "Cetirizine",
      "Claritin",
      "Fexofenadine",
      "Loratadine",
      "Phenergan",
      "Piriton",
      "Promethazine",
      "Telfast",
      "Zyrtec",
      // Cough, cold & respiratory
      "Actifed",
      "Benylin",
      "Bisolvon",
      "Cofsils",
      "Coldact",
      "Inhaler",
      "Piccan",
      "Robitussin",
      "Salbutamol",
      "Strepsils",
      "Ventolin",
      // Antacids / GI
      "Andrews Liver Salt",
      "Buscopan",
      "Combantrin",
      "De-Worm",
      "Flagyl",
      "Gaviscon",
      "Gestid",
      "Hyoscine",
      "Losec",
      "Magnesium Trisilicate",
      "Metronidazole",
      "Milk of Magnesia",
      "Mist Mag",
      "Nexium",
      "Omeprazole",
      "Pantoprazole",
      "Vermox",
      "Zentel",
      // Diabetes
      "Amaryl",
      "Daonil",
      "Diabinese",
      "Diamicron",
      "Glucophage",
      "Metformin",
      // Cardiovascular / hypertension
      "Aldactone",
      "Amlo",
      "Amlodipine",
      "Atorvastatin",
      "Concor",
      "Cozaar",
      "Lasix",
      "Lipitor",
      "Lisinopril",
      "Losartan",
      "Norvasc",
      "Zestril",
      // Antiseptics & first aid
      "Bandage",
      "Cotton Wool",
      "Dettol Antiseptic",
      "Elastoplast",
      "Hydrogen Peroxide",
      "Iodine",
      "Methylated Spirit",
      "Savlon",
      "Surgical Spirit",
      // Skin / dermatologicals
      "Betnovate",
      "Canesten",
      "Clotrimazole",
      "Daktarin",
      "Funbact-A",
      "Hydrocortisone Cream",
      "Ketoconazole Cream",
      "Skineal",
      "Whitfield's Ointment",
      // Eye / ear
      "Chloramphenicol Eye Drops",
      "Otrivin",
      "Sofradex",
      "Visine",
      // Family planning
      "Depo-Provera",
      "Duo-Fem",
      "Microgynon",
      "Postinor-2",
      // Sexual health
      "Durex",
      "Fiesta",
      "K-Y Jelly",
      "Rough Rider",
      // Baby & maternal care
      "Cerelac",
      "Gripe Water",
      "Infacol",
      "Nan Milk",
      "Pears Gripe Water",
      "Pregnacare",
      "Woodwards Gripe Water",
      // Vitamins & supplements
      "Astyfer",
      "Astymin",
      "B-Complex",
      "Blood Tonic",
      "Centrum",
      "Cevit",
      "Chelaforte",
      "Chemiron",
      "Cod Liver Oil",
      "Emzor Vitamin C",
      "Feroglobin",
      "Ferro-F",
      "Fersolate",
      "Folic Acid",
      "Folivit",
      "Gvither",
      "Haemobion",
      "Omega 3",
      "Sangobion",
      "Seven Seas",
      "Surbex",
      "Vitamin C",
      // Corticosteroids
      "Dexa",
      "Dexamethasone",
      "Prednisolone",
      // Diabetes devices / injectables
      "Humulin",
      "Hydrite",
      "Insulin",
      "Mixtard",
      "Oral Rehydration Salt (ORS)",
      // Antiemetics
      "Avomine",
      "L-Artem",
      "Lofem",
      // Miscellaneous well-known brands
      "Chi Vita",
    ],
    generics: [
      "Acetaminophen",
      "Albendazole",
      "Amlodipine",
      "Amoxicillin/Clavulanate",
      "Ampicillin",
      "Artemether/Lumefantrine",
      "Artesunate",
      "Ascorbic Acid",
      "Atenolol",
      "Atorvastatin",
      "Azithromycin",
      "Beclomethasone",
      "Captopril",
      "Carbamazepine",
      "Ceftriaxone",
      "Cefuroxime",
      "Cetirizine",
      "Chloramphenicol",
      "Chlorpheniramine",
      "Ciprofloxacin",
      "Clarithromycin",
      "Clotrimazole",
      "Cloxacillin",
      "Co-trimoxazole",
      "Dexamethasone",
      "Diazepam",
      "Diclofenac Sodium",
      "Digoxin",
      "Doxycycline",
      "Erythromycin",
      "Ferrous Sulphate",
      "Fexofenadine",
      "Fluconazole",
      "Folic Acid",
      "Furosemide",
      "Glibenclamide",
      "Glimepiride",
      "Griseofulvin",
      "Guanfacine",
      "Haloperidol",
      "Hydralazine",
      "Hydrochlorothiazide",
      "Hydrocortisone",
      "Hyoscine Butylbromide",
      "Ibuprofen",
      "Insulin Isophane",
      "Insulin Soluble",
      "Ketoconazole",
      "Lactulose",
      "Levofloxacin",
      "Lisinopril",
      "Loratadine",
      "Losartan",
      "Mebendazole",
      "Metformin",
      "Metformin Hydrochloride",
      "Methyldopa",
      "Metoclopramide",
      "Metronidazole",
      "Multivitamins",
      "Nifedipine",
      "Nystatin",
      "Ofloxacin",
      "Omeprazole",
      "Oral Rehydration Salts",
      "Paracetamol",
      "Piroxicam",
      "Prednisolone",
      "Promethazine",
      "Propranolol",
      "Ranitidine",
      "Salbutamol",
      "Simvastatin",
      "Spironolactone",
      "Tetracycline",
      "Tramadol Hydrochloride",
      "Vitamin B Complex",
      "Vitamin B12",
      "Zinc Sulphate",
    ],
    strengths: [
      "IU",
      "mcg",
      "percentage (%)",
      "units",
      "v/v",
      "w/v",
      "w/w",
      "µg",
      "0.75mg",
      "1.5mg",
      "2.5mg",
      "5mg",
      "5ml",
      "10mg",
      "10ml",
      "12.5mg",
      "15ml",
      "20/120mg",
      "20mg",
      "25mg",
      "30mg",
      "37.5mg",
      "40/240mg",
      "40mg",
      "50mg",
      "50ml",
      "60mg",
      "60ml",
      "75mg",
      "80/480mg",
      "80mg",
      "100mg",
      "100ml",
      "125mg",
      "150mg",
      "150ml",
      "160mg",
      "200mg",
      "200ml",
      "250/500mg",
      "250mg",
      "250ml",
      "300mg",
      "320mg",
      "400mg",
      "450mg",
      "500mg",
      "500ml",
      "600mg",
      "625mg",
      "750mg",
      "800mg",
      "900mg",
      "1g",
      "1.2g",
      "1.5g",
      "2g",
      "3g",
      "4g",
      "5g",
    ],
    categories: [
      "Analgesics",
      "Antacids",
      "Anthelmintics",
      "Anti-diarrheals",
      "Anti-emetics",
      "Antibiotics",
      "Anticonvulsants",
      "Antidepressants",
      "Antidiabetics",
      "Antifungals",
      "Antihistamines",
      "Antihypertensives",
      "Antimalarials",
      "Antiseptics",
      "Antivirals",
      "Baby Care",
      "Cardiovascular",
      "Contraceptives",
      "Corticosteroids",
      "Cough & Cold",
      "Dermatologicals",
      "Diagnostics & Test Kits",
      "Eye/Ear Drops",
      "Family Planning",
      "First Aid",
      "Herbal & Traditional Medicine",
      "Inhalers & Respiratory",
      "Injectables",
      "Laxatives",
      "Medical Devices",
      "Sexual Wellness",
      "Surgicals",
      "Vitamins & Supplements",
    ],
    dosageForms: [
      "Caplet",
      "Capsule",
      "Cream",
      "Drops",
      "Elixir",
      "Gel",
      "Granules",
      "Infusion",
      "Inhaler",
      "Injection",
      "Liniment",
      "Lotion",
      "Lozenge",
      "Ointment",
      "Patch",
      "Pessary",
      "Powder",
      "Sachet",
      "Softgel",
      "Solution",
      "Spray",
      "Suppository",
      "Suspension",
      "Syrup",
      "Tablet",
    ],
    manufacturers: [
      "Agary Pharmaceutical",
      "Ajanta Pharma",
      "AstraZeneca",
      "Bayer",
      "Bond Chemical",
      "Chi Pharmaceuticals",
      "Cipla",
      "Dana Pharmaceuticals",
      "Drugfield Pharmaceuticals",
      "Emzor Pharmaceuticals",
      "Evans Medical",
      "Fidson Healthcare",
      "Geneith Pharmaceuticals",
      "Getz Pharma",
      "Greenlife Pharmaceuticals",
      "GSK Nigeria",
      "Hovid",
      "Juhel Nigeria",
      "M&B",
      "May & Baker Nigeria",
      "Mecure Industries",
      "Micronova Pharmaceuticals",
      "Micro Labs",
      "Morison Industries",
      "Nalis Pharmaceuticals",
      "Neimeth International",
      "Novartis",
      "Orange Drug",
      "Pfizer Nigeria",
      "Pharma-Deko",
      "Ranbaxy (Sun Pharma)",
      "Reals Pharmaceuticals",
      "Roche",
      "Sam Pharmaceutical",
      "Sanofi Nigeria",
      "Shalina Healthcare",
      "SKG Pharma",
      "Strides Shasun",
      "Swiss Pharma (Swipha)",
      "Triveni",
      "Unique Pharma",
      "Vanguard Store",
      "Zolon Healthcare",
    ],
  },
  retail: {
    names: [
      // Soft drinks & water
      "7Up",
      "Aquafina",
      "Bigi Cola",
      "Bigi Drinks",
      "Coca-Cola",
      "Cway Water",
      "Eva Water",
      "Fanta",
      "La Casera",
      "Mirinda",
      "Nutri C",
      "Pepsi",
      "Predator",
      "Premier Cool",
      "Sprite",
      "Teem",
      "Viju Milk",
      // Beer & malt
      "Amstel Malta",
      "Dubic Malt",
      "Gulder",
      "Guinness Stout",
      "Hero Lager",
      "Legend Extra Stout",
      "Malta Guinness",
      "Maltina",
      "Star Lager",
      "Trophy Lager",
      // Dairy & milk
      "Dano Milk",
      "Loya Milk",
      "Peak Liquid",
      "Peak Milk",
      "Three Crowns Milk",
      // Cereals, spreads & breakfast
      "Blue Band",
      "Cornflakes",
      "Golden Morn",
      "Kellogg's Corn Flakes",
      "Milo",
      // Noodles & instant food
      "Indomie Chicken",
      "Indomie Noodles",
      "Indomie Onion",
      "Indomie Super Pack",
      "Minimie Noodles",
      "Chikki Noodles",
      // Seasoning & cooking
      "Bouillon Cubes",
      "Devon King's Oil",
      "Gino Oil",
      "Gino Tomato Paste",
      "Kings Vegetable Oil",
      "Knorr",
      "Maggi",
      "Maggi Crayfish",
      "Maggi Star",
      "Mamador Oil",
      "Power Oil",
      // Custard & confectionery
      "Checkers Custard",
      "Fun Cookies",
      "Gala Sausage Roll",
      "Lady B Custard",
      // Baby products
      "Fine Baby Diapers",
      "Johnson's Baby",
      "Molfix Diapers",
      "Pampers",
      "Pears Baby Oil",
      // Sanitary & personal care
      "Always Sanitary Pad",
      "Colgate",
      "Close Up",
      "Dettol Soap",
      "Joy Soap",
      "Lux Soap",
      "Macleans",
      "MyMy",
      "Oral B",
      "Pears Soap",
      "Premier Cool Soap",
      "Rexona",
      // Household cleaning
      "Air Wick",
      "Ariel Detergent",
      "Harpic",
      "Hypo Bleach",
      "Jik",
      "Morning Fresh",
      "Omo",
      "Sunlight Detergent",
      "Venus",
      // Sexual wellness
      "Fiesta",
      "Rough Rider",
      // Motor spirit & fuel add-ons (for stores that sell recharge/utility items)
      "Recharge Card MTN",
      "Recharge Card Airtel",
      "Recharge Card Glo",
      "Recharge Card 9mobile",
    ],
    generics: [],
    strengths: [
      "Economy",
      "Family Pack",
      "Jumbo",
      "Large",
      "Medium",
      "Sachet",
      "Small",
      "33cl",
      "35cl",
      "50cl",
      "60cl",
      "75cl",
      "1L",
      "1.5L",
      "2L",
      "5L",
      "20L",
      "25g",
      "70g",
      "120g",
      "150g",
      "200g",
      "400g",
      "450g",
      "500g",
      "900g",
      "1kg",
      "2kg",
      "5kg",
      "10kg",
      "25kg",
      "50kg",
    ],
    categories: [
      "Baby Products",
      "Beer & Malt",
      "Beverages",
      "Cereals",
      "Cleaning Agents",
      "Confectionery",
      "Dairy",
      "Detergents",
      "Food & Spices",
      "Grains & Pasta",
      "Groceries",
      "Household",
      "Kitchenware",
      "Laundry",
      "Noodles",
      "Oils & Fats",
      "Personal Care",
      "Recharge Cards & Airtime",
      "Sanitary Products",
      "Snacks",
      "Soft Drinks",
      "Stationery",
      "Toiletries",
      "Water",
    ],
    dosageForms: [],
    manufacturers: [
      "BUA Group",
      "Beloxxi Industries",
      "British American Tobacco Nigeria",
      "Cadbury Nigeria",
      "Chi Limited",
      "Coca-Cola Hellenic",
      "Dangote Group",
      "Dansa Foods",
      "Dufil Prima Foods",
      "Flour Mills of Nigeria",
      "Grand Cereals",
      "Guinness Nigeria",
      "Honeywell Flour Mills",
      "International Breweries",
      "Multipro Consumer",
      "Nasco Group",
      "Nestle Nigeria",
      "Nigerian Breweries",
      "Ok Foods",
      "Promasidor",
      "PZ Cussons",
      "Rite Foods",
      "Seven-Up Bottling Company",
      "TGI Group",
      "Tolaram Group",
      "UAC Foods",
      "Unilever Nigeria",
      "Vital Products",
      "Yale Foods",
    ],
  },
  common: {
    units: [
      "Ampoule",
      "Bag",
      "Bottle",
      "Box",
      "Bundle",
      "Can",
      "Caplet",
      "Capsule",
      "Card",
      "Carton",
      "Crate",
      "Dozen",
      "Drum",
      "Jar",
      "Pack",
      "Piece",
      "Roll",
      "Sachet",
      "Set",
      "Spoonful",
      "Tablet",
      "Tin",
      "Tray",
      "Tube",
      "Vial",
    ],
    locations: [
      "Aba",
      "Abakaliki",
      "Abeokuta",
      "Abiriba",
      "Abor",
      "Abraka",
      "Abuja",
      "Ado-Ekiti",
      "Afikpo",
      "Agbani",
      "Agbogugu",
      "Aguleri",
      "Ahoada",
      "Akure",
      "Amasiri",
      "Anara",
      "Arochukwu",
      "Asaba",
      "Atani",
      "Awgu",
      "Awka",
      "Azare",
      "Bali",
      "Bama",
      "Bauchi",
      "Bende",
      "Benin City",
      "Bida",
      "Birnin Kebbi",
      "Biu",
      "Bonny",
      "Buguma",
      "Bukuru",
      "Calabar",
      "Damaturu",
      "Dutse",
      "Edda",
      "Effurun",
      "Egbeda",
      "Ejigbo",
      "Ekwulobia",
      "Emene",
      "Enugu",
      "Epe",
      "Eket",
      "Gashua",
      "Gboko",
      "Gombe",
      "Gusau",
      "Gwagwalada",
      "Ibadan",
      "Igboukwu",
      "Ihiala",
      "Ijebu-Ode",
      "Ikeja",
      "Ikirun",
      "Ikom",
      "Ikorodu",
      "Ikwo",
      "Ikwuano",
      "Ilesa",
      "Ilorin",
      "Ishiagu",
      "Iseyin",
      "Isolo",
      "Iwo",
      "Jalingo",
      "Jos",
      "Kaduna",
      "Kano",
      "Katsina",
      "Keffi",
      "Lafia",
      "Lagos",
      "Lokoja",
      "Maiduguri",
      "Makurdi",
      "Mbaise",
      "Minna",
      "Mubi",
      "Nkalagu",
      "Nkpor",
      "Nnewi",
      "Nsukka",
      "Numan",
      "Obosi",
      "Ogbomoso",
      "Ogidi",
      "Oguta",
      "Ohafia",
      "Oji",
      "Oji River",
      "Okene",
      "Okigwe",
      "Oko",
      "Okposi",
      "Omoba",
      "Onitsha",
      "Onueke",
      "Opobo",
      "Oraifite",
      "Orlu",
      "Oron",
      "Osogbo",
      "Otukpo",
      "Owerri",
      "Owo",
      "Oyo",
      "Ozubulu",
      "Port Harcourt",
      "Potiskum",
      "Sagamu",
      "Sapele",
      "Shagamu",
      "Shaki",
      "Shendam",
      "Sokoto",
      "Suleja",
      "Uburu",
      "Udi",
      "Ugep",
      "Ughelli",
      "Umuahia",
      "Umuleri",
      "Umunze",
      "Umuoji",
      "Uromi",
      "Uyo",
      "Wamba",
      "Warri",
      "Yenagoa",
      "Yola",
      "Zaria",
      "Zuru",
    ],
    states: [
      "Abia State",
      "Adamawa State",
      "Akwa Ibom State",
      "Anambra State",
      "Bauchi State",
      "Bayelsa State",
      "Benue State",
      "Borno State",
      "Cross River State",
      "Delta State",
      "Ebonyi State",
      "Edo State",
      "Ekiti State",
      "Enugu State",
      "FCT - Abuja",
      "Gombe State",
      "Imo State",
      "Jigawa State",
      "Kaduna State",
      "Kano State",
      "Katsina State",
      "Kebbi State",
      "Kogi State",
      "Kwara State",
      "Lagos State",
      "Nasarawa State",
      "Niger State",
      "Ogun State",
      "Ondo State",
      "Osun State",
      "Oyo State",
      "Plateau State",
      "Rivers State",
      "Sokoto State",
      "Taraba State",
      "Yobe State",
      "Zamfara State",
    ],
  },
};

export const NIGERIAN_BANKS = [
  "Access Bank",
  "ALAT by WEMA",
  "Baobab Microfinance Bank",
  "Carbon",
  "Citibank Nigeria",
  "Coronation Merchant Bank",
  "Ecobank Nigeria",
  "Eyowo",
  "FairMoney",
  "Fidelity Bank",
  "Fina Trust Microfinance Bank",
  "First Bank of Nigeria",
  "First City Monument Bank (FCMB)",
  "FSDH Merchant Bank",
  "Globus Bank",
  "Guaranty Trust Bank (GTB)",
  "Jaiz Bank",
  "Keystone Bank",
  "Kuda Bank",
  "LAPO Microfinance Bank",
  "Lotus Bank",
  "Mint (formerly Mint-FSDH)",
  "Moniepoint",
  "Nova Merchant Bank",
  "Opay",
  "Optimus Bank",
  "Palmpay",
  "Parallex Bank",
  "Paga",
  "Pocket App",
  "Polaris Bank",
  "PremiumTrust Bank",
  "Providus Bank",
  "PiggyVest",
  "Rand Merchant Bank",
  "Renmoney",
  "Rubies Bank",
  "Signature Bank",
  "Sparkle",
  "Stanbic IBTC Bank",
  "Standard Chartered Bank",
  "Sterling Bank",
  "SunTrust Bank",
  "TAJBank",
  "Titan Trust Bank",
  "Union Bank of Nigeria",
  "United Bank for Africa (UBA)",
  "Unity Bank",
  "VFD Microfinance Bank",
  "Wema Bank",
  "Zenith Bank",
];
