/* eslint-disable max-lines */
export const FORM_SUGGESTIONS = {
  store: {
    products: [
      // Analgesics / pain & fever
      {
        name: "Advil",
        genericName: "Ibuprofen",
        manufacturer: "Pfizer",
        strength: "200mg",
        dosageForm: "Caplet",
      },
      { name: "Andrews Answer" },
      { name: "Cafenol" },
      {
        name: "Cataflam",
        genericName: "Diclofenac Potassium",
        manufacturer: "Novartis",
        strength: "50mg",
        dosageForm: "Tablet",
      },
      { name: "Diclo Sodium" },
      { name: "Diclofenac" },
      {
        name: "Emzor Paracetamol",
        genericName: "Paracetamol",
        manufacturer: "Emzor Pharmaceuticals",
        strength: "500mg",
        dosageForm: "Tablet",
      },
      {
        name: "Feldene",
        genericName: "Piroxicam",
        manufacturer: "Pfizer",
        strength: "20mg",
        dosageForm: "Capsule",
      },
      { name: "Fem-1" },
      { name: "Flexi Rub" },
      { name: "Ibu" },
      { name: "Ibuprofen" },
      { name: "Naproxen" },
      { name: "Novalgin" },
      {
        name: "Nurofen",
        genericName: "Ibuprofen",
        manufacturer: "Reckitt Benckiser",
        strength: "200mg",
        dosageForm: "Tablet",
      },
      { name: "P-Alaxin" },
      {
        name: "Panadol",
        genericName: "Paracetamol",
        manufacturer: "GSK",
        strength: "500mg",
        dosageForm: "Tablet",
      },
      {
        name: "Panadol Child",
        genericName: "Paracetamol",
        manufacturer: "GSK",
        strength: "120mg/5ml",
        dosageForm: "Syrup",
      },
      {
        name: "Panadol Extra",
        genericName: "Paracetamol + Caffeine",
        manufacturer: "GSK",
        strength: "500mg/65mg",
        dosageForm: "Caplet",
      },
      { name: "Paracetamol" },
      { name: "Piroxicam" },
      { name: "Reme" },
      { name: "Tramadol" },
      {
        name: "Voltaren",
        genericName: "Diclofenac",
        manufacturer: "Novartis",
        strength: "50mg",
        dosageForm: "Tablet",
      },
      // Antimalarials
      {
        name: "Amatem",
        genericName: "Artemether/Lumefantrine",
        manufacturer: "May & Baker Nigeria",
        dosageForm: "Tablet",
      },
      {
        name: "Amatem Softgel",
        genericName: "Artemether/Lumefantrine",
        manufacturer: "May & Baker Nigeria",
        dosageForm: "Softgel",
      },
      { name: "Artemether/Lumefantrine" },
      { name: "Artesun" },
      { name: "Artesunate" },
      { name: "Camosunate" },
      {
        name: "Coartem",
        genericName: "Artemether + Lumefantrine",
        manufacturer: "Novartis",
        strength: "20mg/120mg",
        dosageForm: "Tablet",
      },
      {
        name: "Coartem 80/480",
        genericName: "Artemether + Lumefantrine",
        manufacturer: "Novartis",
        strength: "80mg/480mg",
        dosageForm: "Tablet",
      },
      { name: "Duo-Cotecxin" },
      {
        name: "Fansidar",
        genericName: "Sulfadoxine/Pyrimethamine",
        manufacturer: "Roche",
        dosageForm: "Tablet",
      },
      { name: "Green Cap" },
      { name: "Jonnys Cool" },
      {
        name: "Lonart",
        genericName: "Artemether/Lumefantrine",
        manufacturer: "Greenlife Pharmaceuticals",
        dosageForm: "Tablet",
      },
      {
        name: "Lonart DS",
        genericName: "Artemether/Lumefantrine",
        manufacturer: "Greenlife Pharmaceuticals",
        dosageForm: "Tablet",
      },
      { name: "Lumartem" },
      { name: "Malareich" },
      { name: "P-Alaxin Forte", manufacturer: "Swiss Pharma (Swipha)" },
      // Antibiotics
      { name: "Amoxicillin" },
      {
        name: "Amoxil",
        genericName: "Amoxicillin",
        manufacturer: "GSK",
        strength: "500mg",
        dosageForm: "Capsule",
      },
      { name: "Ampicillin" },
      { name: "Ampiclox" },
      { name: "Ampliclox" },
      {
        name: "Augmentin",
        genericName: "Amoxicillin + Clavulanate Potassium",
        manufacturer: "GSK",
        strength: "625mg",
        dosageForm: "Tablet",
      },
      {
        name: "Augmentin 1g",
        genericName: "Amoxicillin + Clavulanate Potassium",
        manufacturer: "GSK",
        strength: "1g",
        dosageForm: "Tablet",
      },
      {
        name: "Augmentin 625mg",
        genericName: "Amoxicillin + Clavulanate Potassium",
        manufacturer: "GSK",
        strength: "625mg",
        dosageForm: "Tablet",
      },
      { name: "Azithro" },
      { name: "Azithromycin" },
      { name: "Bactrim" },
      {
        name: "Beecham Ampiclox",
        genericName: "Ampicillin/Cloxacillin",
        manufacturer: "GSK",
        dosageForm: "Capsule",
      },
      { name: "Ceftriaxone" },
      { name: "Cefuroxime" },
      { name: "Ciproflox" },
      { name: "Ciprofloxacin" },
      {
        name: "Ciprotab",
        genericName: "Ciprofloxacin",
        manufacturer: "Bond Chemical",
        strength: "500mg",
        dosageForm: "Tablet",
      },
      { name: "Cloxacillin" },
      { name: "Doxycycline" },
      { name: "Erythrocin" },
      {
        name: "Floxapen",
        genericName: "Flucloxacillin",
        manufacturer: "GSK",
        dosageForm: "Capsule",
      },
      { name: "Gentamicin" },
      {
        name: "Klacid",
        genericName: "Clarithromycin",
        manufacturer: "AbbVie",
        dosageForm: "Tablet",
      },
      { name: "Neomycin" },
      { name: "Norfloxacin" },
      { name: "Ofloxacin" },
      {
        name: "Peflacine",
        genericName: "Pefloxacin",
        manufacturer: "Sanofi Nigeria",
        dosageForm: "Tablet",
      },
      {
        name: "Rocephin",
        genericName: "Ceftriaxone",
        manufacturer: "Roche",
        dosageForm: "Injection",
      },
      {
        name: "Septrin",
        genericName: "Co-trimoxazole",
        manufacturer: "GSK",
        dosageForm: "Tablet",
      },
      {
        name: "Tarivid",
        genericName: "Ofloxacin",
        manufacturer: "Sanofi Nigeria",
        dosageForm: "Tablet",
      },
      {
        name: "Vibramycin",
        genericName: "Doxycycline",
        manufacturer: "Pfizer",
        dosageForm: "Capsule",
      },
      {
        name: "Zinacef",
        genericName: "Cefuroxime",
        manufacturer: "GSK",
        dosageForm: "Injection",
      },
      {
        name: "Zinnat",
        genericName: "Cefuroxime",
        manufacturer: "GSK",
        dosageForm: "Tablet",
      },
      {
        name: "Zithromax",
        genericName: "Azithromycin",
        manufacturer: "Pfizer",
        dosageForm: "Tablet",
      },
      // Antihistamines / allergy
      { name: "Cetirizine" },
      {
        name: "Claritin",
        genericName: "Loratadine",
        manufacturer: "Bayer",
        dosageForm: "Tablet",
      },
      { name: "Fexofenadine" },
      { name: "Loratadine" },
      {
        name: "Phenergan",
        genericName: "Promethazine",
        manufacturer: "Sanofi Nigeria",
        dosageForm: "Syrup",
      },
      { name: "Piriton" },
      { name: "Promethazine" },
      {
        name: "Telfast",
        genericName: "Fexofenadine",
        manufacturer: "Sanofi Nigeria",
        dosageForm: "Tablet",
      },
      {
        name: "Zyrtec",
        genericName: "Cetirizine",
        manufacturer: "GSK",
        dosageForm: "Tablet",
      },
      // Cough, cold & respiratory
      { name: "Actifed" },
      {
        name: "Benylin",
        manufacturer: "Kenvue (Johnson & Johnson)",
        dosageForm: "Syrup",
      },
      { name: "Bisolvon" },
      { name: "Cofsils" },
      { name: "Coldact" },
      { name: "Inhaler" },
      { name: "Piccan" },
      {
        name: "Robitussin",
        manufacturer: "Haleon (GSK Consumer)",
        dosageForm: "Syrup",
      },
      { name: "Salbutamol" },
      {
        name: "Strepsils",
        manufacturer: "Reckitt Benckiser",
        dosageForm: "Lozenge",
      },
      {
        name: "Ventolin",
        genericName: "Salbutamol",
        manufacturer: "GSK",
        dosageForm: "Inhaler",
      },
      // Antacids / GI
      { name: "Andrews Liver Salt" },
      {
        name: "Buscopan",
        genericName: "Hyoscine Butylbromide",
        manufacturer: "Sanofi Nigeria",
        dosageForm: "Tablet",
      },
      { name: "Combantrin" },
      { name: "De-Worm" },
      {
        name: "Flagyl",
        genericName: "Metronidazole",
        manufacturer: "Sanofi Nigeria",
        dosageForm: "Tablet",
      },
      {
        name: "Gaviscon",
        manufacturer: "Reckitt Benckiser",
        dosageForm: "Suspension",
      },
      { name: "Gestid" },
      { name: "Hyoscine" },
      {
        name: "Losec",
        genericName: "Omeprazole",
        manufacturer: "AstraZeneca",
        dosageForm: "Capsule",
      },
      { name: "Magnesium Trisilicate" },
      { name: "Metronidazole" },
      { name: "Milk of Magnesia" },
      { name: "Mist Mag" },
      {
        name: "Nexium",
        genericName: "Esomeprazole",
        manufacturer: "AstraZeneca",
        dosageForm: "Tablet",
      },
      { name: "Omeprazole" },
      { name: "Pantoprazole" },
      { name: "Vermox" },
      { name: "Zentel" },
      // Diabetes
      {
        name: "Amaryl",
        genericName: "Glimepiride",
        manufacturer: "Sanofi Nigeria",
        dosageForm: "Tablet",
      },
      {
        name: "Daonil",
        genericName: "Glibenclamide",
        manufacturer: "Sanofi Nigeria",
        dosageForm: "Tablet",
      },
      { name: "Diabinese" },
      {
        name: "Diamicron",
        genericName: "Gliclazide",
        manufacturer: "Servier",
        dosageForm: "Tablet",
      },
      {
        name: "Glucophage",
        genericName: "Metformin",
        manufacturer: "Merck",
        dosageForm: "Tablet",
      },
      { name: "Metformin" },
      // Cardiovascular / hypertension
      {
        name: "Aldactone",
        genericName: "Spironolactone",
        manufacturer: "Pfizer",
        dosageForm: "Tablet",
      },
      { name: "Amlo" },
      { name: "Amlodipine" },
      { name: "Atorvastatin" },
      {
        name: "Concor",
        genericName: "Bisoprolol",
        manufacturer: "Merck",
        dosageForm: "Tablet",
      },
      {
        name: "Cozaar",
        genericName: "Losartan",
        manufacturer: "Merck",
        dosageForm: "Tablet",
      },
      {
        name: "Lasix",
        genericName: "Furosemide",
        manufacturer: "Sanofi Nigeria",
        dosageForm: "Tablet",
      },
      {
        name: "Lipitor",
        genericName: "Atorvastatin",
        manufacturer: "Pfizer",
        dosageForm: "Tablet",
      },
      { name: "Lisinopril" },
      { name: "Losartan" },
      {
        name: "Norvasc",
        genericName: "Amlodipine",
        manufacturer: "Pfizer",
        dosageForm: "Tablet",
      },
      {
        name: "Zestril",
        genericName: "Lisinopril",
        manufacturer: "AstraZeneca",
        dosageForm: "Tablet",
      },
      // Antiseptics & first aid
      { name: "Bandage" },
      { name: "Cotton Wool" },
      { name: "Dettol Antiseptic", manufacturer: "Reckitt Benckiser" },
      { name: "Elastoplast", manufacturer: "Beiersdorf" },
      { name: "Hydrogen Peroxide" },
      { name: "Iodine" },
      { name: "Methylated Spirit" },
      { name: "Savlon", manufacturer: "Johnson & Johnson" },
      { name: "Surgical Spirit" },
      // Skin / dermatologicals
      {
        name: "Betnovate",
        genericName: "Betamethasone",
        manufacturer: "GSK",
        dosageForm: "Cream",
      },
      {
        name: "Canesten",
        genericName: "Clotrimazole",
        manufacturer: "Bayer",
        dosageForm: "Cream",
      },
      { name: "Clotrimazole" },
      {
        name: "Daktarin",
        genericName: "Miconazole",
        manufacturer: "Johnson & Johnson",
        dosageForm: "Cream",
      },
      { name: "Funbact-A" },
      { name: "Hydrocortisone Cream" },
      { name: "Ketoconazole Cream" },
      { name: "Skineal" },
      { name: "Whitfield's Ointment" },
      // Eye / ear
      { name: "Chloramphenicol Eye Drops" },
      {
        name: "Otrivin",
        genericName: "Xylometazoline",
        manufacturer: "Haleon (GSK Consumer)",
        dosageForm: "Spray",
      },
      { name: "Sofradex" },
      { name: "Visine", manufacturer: "Johnson & Johnson" },
      // Family planning
      {
        name: "Depo-Provera",
        genericName: "Medroxyprogesterone",
        manufacturer: "Pfizer",
        dosageForm: "Injection",
      },
      { name: "Duo-Fem" },
      {
        name: "Microgynon",
        genericName: "Ethinylestradiol/Levonorgestrel",
        manufacturer: "Bayer",
        dosageForm: "Tablet",
      },
      {
        name: "Postinor-2",
        genericName: "Levonorgestrel",
        manufacturer: "Gedeon Richter",
        dosageForm: "Tablet",
      },
      // Sexual health
      { name: "Durex", manufacturer: "Reckitt Benckiser" },
      { name: "Fiesta" },
      { name: "K-Y Jelly", manufacturer: "Reckitt Benckiser" },
      { name: "Rough Rider" },
      // Baby & maternal care
      { name: "Cerelac", manufacturer: "Nestle Nigeria" },
      { name: "Gripe Water" },
      { name: "Infacol" },
      { name: "Nan Milk", manufacturer: "Nestle Nigeria" },
      { name: "Pears Gripe Water" },
      { name: "Pregnacare", manufacturer: "Vitabiotics" },
      { name: "Woodwards Gripe Water" },
      // Vitamins & supplements
      { name: "Astyfer" },
      { name: "Astymin" },
      { name: "B-Complex" },
      { name: "Blood Tonic" },
      {
        name: "Centrum",
        manufacturer: "Haleon (GSK Consumer)",
        dosageForm: "Tablet",
      },
      { name: "Cevit" },
      { name: "Chelaforte" },
      { name: "Chemiron" },
      { name: "Cod Liver Oil" },
      {
        name: "Emzor Vitamin C",
        genericName: "Ascorbic Acid",
        manufacturer: "Emzor Pharmaceuticals",
        dosageForm: "Tablet",
      },
      { name: "Feroglobin", manufacturer: "Vitabiotics" },
      { name: "Ferro-F" },
      { name: "Fersolate" },
      { name: "Folic Acid" },
      { name: "Folivit" },
      { name: "Gvither" },
      { name: "Haemobion" },
      { name: "Omega 3" },
      {
        name: "Sangobion",
        genericName: "Ferrous Gluconate + Vitamins",
        manufacturer: "Merck",
        dosageForm: "Capsule",
      },
      { name: "Seven Seas", manufacturer: "Merck", dosageForm: "Capsule" },
      { name: "Surbex", manufacturer: "Abbott", dosageForm: "Tablet" },
      { name: "Vitamin C" },
      // Corticosteroids
      { name: "Dexa" },
      { name: "Dexamethasone" },
      { name: "Prednisolone" },
      // Diabetes devices / injectables
      { name: "Humulin", manufacturer: "Eli Lilly", dosageForm: "Injection" },
      { name: "Hydrite" },
      { name: "Insulin" },
      {
        name: "Mixtard",
        manufacturer: "Novo Nordisk",
        dosageForm: "Injection",
      },
      { name: "Oral Rehydration Salt (ORS)" },
      // Antiemetics
      {
        name: "Avomine",
        genericName: "Promethazine",
        manufacturer: "Sanofi Nigeria",
        dosageForm: "Tablet",
      },
      { name: "L-Artem" },
      { name: "Lofem" },
      // Miscellaneous well-known brands
      { name: "Chi Vita", manufacturer: "Chi Limited" },
    ],
    generics: [
      "Acetaminophen",
      "Albendazole",
      "Amlodipine",
      "Amoxicillin/Clavulanate",
      "Ampicillin",
      "Artemether/Lumefantrine",
      "Artesunate",
      "Ascorbic Acid",
      "Atenolol",
      "Atorvastatin",
      "Azithromycin",
      "Beclomethasone",
      "Captopril",
      "Carbamazepine",
      "Ceftriaxone",
      "Cefuroxime",
      "Cetirizine",
      "Chloramphenicol",
      "Chlorpheniramine",
      "Ciprofloxacin",
      "Clarithromycin",
      "Clotrimazole",
      "Cloxacillin",
      "Co-trimoxazole",
      "Dexamethasone",
      "Diazepam",
      "Diclofenac Sodium",
      "Digoxin",
      "Doxycycline",
      "Erythromycin",
      "Ferrous Sulphate",
      "Fexofenadine",
      "Fluconazole",
      "Folic Acid",
      "Furosemide",
      "Glibenclamide",
      "Glimepiride",
      "Griseofulvin",
      "Guanfacine",
      "Haloperidol",
      "Hydralazine",
      "Hydrochlorothiazide",
      "Hydrocortisone",
      "Hyoscine Butylbromide",
      "Ibuprofen",
      "Insulin Isophane",
      "Insulin Soluble",
      "Ketoconazole",
      "Lactulose",
      "Levofloxacin",
      "Lisinopril",
      "Loratadine",
      "Losartan",
      "Mebendazole",
      "Metformin",
      "Metformin Hydrochloride",
      "Methyldopa",
      "Metoclopramide",
      "Metronidazole",
      "Multivitamins",
      "Nifedipine",
      "Nystatin",
      "Ofloxacin",
      "Omeprazole",
      "Oral Rehydration Salts",
      "Paracetamol",
      "Piroxicam",
      "Prednisolone",
      "Promethazine",
      "Propranolol",
      "Ranitidine",
      "Salbutamol",
      "Simvastatin",
      "Spironolactone",
      "Tetracycline",
      "Tramadol Hydrochloride",
      "Vitamin B Complex",
      "Vitamin B12",
      "Zinc Sulphate",
    ],
    strengths: [
      "IU",
      "mcg",
      "percentage (%)",
      "units",
      "v/v",
      "w/v",
      "w/w",
      "µg",
      "0.75mg",
      "1.5mg",
      "2.5mg",
      "5mg",
      "5ml",
      "10mg",
      "10ml",
      "12.5mg",
      "15ml",
      "20/120mg",
      "20mg",
      "25mg",
      "30mg",
      "37.5mg",
      "40/240mg",
      "40mg",
      "50mg",
      "50ml",
      "60mg",
      "60ml",
      "75mg",
      "80/480mg",
      "80mg",
      "100mg",
      "100ml",
      "125mg",
      "150mg",
      "150ml",
      "160mg",
      "200mg",
      "200ml",
      "250/500mg",
      "250mg",
      "250ml",
      "300mg",
      "320mg",
      "400mg",
      "450mg",
      "500mg",
      "500ml",
      "600mg",
      "625mg",
      "750mg",
      "800mg",
      "900mg",
      "1g",
      "1.2g",
      "1.5g",
      "2g",
      "3g",
      "4g",
      "5g",
    ],
    categories: [
      "Analgesics",
      "Antacids",
      "Anthelmintics",
      "Anti-diarrheals",
      "Anti-emetics",
      "Antibiotics",
      "Anticonvulsants",
      "Antidepressants",
      "Antidiabetics",
      "Antifungals",
      "Antihistamines",
      "Antihypertensives",
      "Antimalarials",
      "Antiseptics",
      "Antivirals",
      "Baby Care",
      "Cardiovascular",
      "Contraceptives",
      "Corticosteroids",
      "Cough & Cold",
      "Dermatologicals",
      "Diagnostics & Test Kits",
      "Eye/Ear Drops",
      "Family Planning",
      "First Aid",
      "Herbal & Traditional Medicine",
      "Inhalers & Respiratory",
      "Injectables",
      "Laxatives",
      "Medical Devices",
      "Sexual Wellness",
      "Surgicals",
      "Vitamins & Supplements",
    ],
    dosageForms: [
      "Caplet",
      "Capsule",
      "Cream",
      "Drops",
      "Elixir",
      "Gel",
      "Granules",
      "Infusion",
      "Inhaler",
      "Injection",
      "Liniment",
      "Lotion",
      "Lozenge",
      "Ointment",
      "Patch",
      "Pessary",
      "Powder",
      "Sachet",
      "Softgel",
      "Solution",
      "Spray",
      "Suppository",
      "Suspension",
      "Syrup",
      "Tablet",
    ],
    manufacturers: [
      "Agary Pharmaceutical",
      "Ajanta Pharma",
      "AstraZeneca",
      "Bayer",
      "Bond Chemical",
      "Chi Pharmaceuticals",
      "Cipla",
      "Dana Pharmaceuticals",
      "Drugfield Pharmaceuticals",
      "Emzor Pharmaceuticals",
      "Evans Medical",
      "Fidson Healthcare",
      "Geneith Pharmaceuticals",
      "Getz Pharma",
      "Greenlife Pharmaceuticals",
      "GSK Nigeria",
      "Hovid",
      "Juhel Nigeria",
      "M&B",
      "May & Baker Nigeria",
      "Mecure Industries",
      "Micronova Pharmaceuticals",
      "Micro Labs",
      "Morison Industries",
      "Nalis Pharmaceuticals",
      "Neimeth International",
      "Novartis",
      "Orange Drug",
      "Pfizer Nigeria",
      "Pharma-Deko",
      "Ranbaxy (Sun Pharma)",
      "Reals Pharmaceuticals",
      "Roche",
      "Sam Pharmaceutical",
      "Sanofi Nigeria",
      "Shalina Healthcare",
      "SKG Pharma",
      "Strides Shasun",
      "Swiss Pharma (Swipha)",
      "Triveni",
      "Unique Pharma",
      "Vanguard Store",
      "Zolon Healthcare",
    ],
  },
  retail: {
    products: [
      // Soft drinks & water
      { name: "7Up", manufacturer: "Seven-Up Bottling Company" },
      { name: "Aquafina", manufacturer: "Seven-Up Bottling Company" },
      { name: "Bigi Cola", manufacturer: "Rite Foods" },
      { name: "Bigi Drinks", manufacturer: "Rite Foods" },
      { name: "Coca-Cola", manufacturer: "Coca-Cola Hellenic" },
      { name: "Cway Water", manufacturer: "CWAY Group" },
      { name: "Eva Water", manufacturer: "Nestle Nigeria" },
      { name: "Fanta", manufacturer: "Coca-Cola Hellenic" },
      { name: "La Casera", manufacturer: "La Casera Company" },
      { name: "Mirinda", manufacturer: "Seven-Up Bottling Company" },
      { name: "Nutri C" },
      { name: "Pepsi", manufacturer: "Seven-Up Bottling Company" },
      { name: "Predator" },
      { name: "Premier Cool" },
      { name: "Sprite", manufacturer: "Coca-Cola Hellenic" },
      { name: "Teem", manufacturer: "Seven-Up Bottling Company" },
      { name: "Viju Milk", manufacturer: "Rite Foods" },
      // Beer & malt
      { name: "Amstel Malta", manufacturer: "Nigerian Breweries" },
      { name: "Dubic Malt" },
      { name: "Gulder", manufacturer: "Nigerian Breweries" },
      { name: "Guinness Stout", manufacturer: "Guinness Nigeria" },
      { name: "Hero Lager", manufacturer: "International Breweries" },
      { name: "Legend Extra Stout", manufacturer: "Nigerian Breweries" },
      { name: "Malta Guinness", manufacturer: "Guinness Nigeria" },
      { name: "Maltina", manufacturer: "Nigerian Breweries" },
      { name: "Star Lager", manufacturer: "Nigerian Breweries" },
      { name: "Trophy Lager", manufacturer: "International Breweries" },
      // Dairy & milk
      { name: "Dano Milk" },
      { name: "Loya Milk" },
      { name: "Peak Liquid", manufacturer: "FrieslandCampina WAMCO" },
      { name: "Peak Milk", manufacturer: "FrieslandCampina WAMCO" },
      { name: "Three Crowns Milk", manufacturer: "FrieslandCampina WAMCO" },
      // Cereals, spreads & breakfast
      { name: "Blue Band", manufacturer: "Unilever Nigeria" },
      { name: "Cornflakes" },
      { name: "Golden Morn", manufacturer: "Nestle Nigeria" },
      { name: "Kellogg's Corn Flakes", manufacturer: "Kellogg's" },
      { name: "Milo", manufacturer: "Nestle Nigeria" },
      // Noodles & instant food
      { name: "Indomie Chicken", manufacturer: "Dufil Prima Foods" },
      { name: "Indomie Noodles", manufacturer: "Dufil Prima Foods" },
      { name: "Indomie Onion", manufacturer: "Dufil Prima Foods" },
      { name: "Indomie Super Pack", manufacturer: "Dufil Prima Foods" },
      { name: "Minimie Noodles", manufacturer: "Dufil Prima Foods" },
      { name: "Chikki Noodles" },
      // Seasoning & cooking
      { name: "Bouillon Cubes" },
      { name: "Devon King's Oil" },
      { name: "Gino Oil", manufacturer: "Erisco Foods" },
      { name: "Gino Tomato Paste", manufacturer: "Erisco Foods" },
      { name: "Kings Vegetable Oil" },
      { name: "Knorr", manufacturer: "Unilever Nigeria" },
      { name: "Maggi", manufacturer: "Nestle Nigeria" },
      { name: "Maggi Crayfish", manufacturer: "Nestle Nigeria" },
      { name: "Maggi Star", manufacturer: "Nestle Nigeria" },
      { name: "Mamador Oil", manufacturer: "PZ Wilmar" },
      { name: "Power Oil" },
      // Custard & confectionery
      { name: "Checkers Custard" },
      { name: "Fun Cookies", manufacturer: "Fastizers Food and Confectionery" },
      { name: "Gala Sausage Roll", manufacturer: "UAC Foods" },
      { name: "Lady B Custard" },
      // Baby products
      { name: "Fine Baby Diapers" },
      { name: "Johnson's Baby", manufacturer: "Kenvue (Johnson & Johnson)" },
      { name: "Molfix Diapers", manufacturer: "Hayat Kimya" },
      { name: "Pampers", manufacturer: "Procter & Gamble" },
      { name: "Pears Baby Oil", manufacturer: "Unilever Nigeria" },
      // Sanitary & personal care
      { name: "Always Sanitary Pad", manufacturer: "Procter & Gamble" },
      { name: "Colgate", manufacturer: "Colgate-Palmolive" },
      { name: "Close Up", manufacturer: "Unilever Nigeria" },
      { name: "Dettol Soap", manufacturer: "Reckitt Benckiser" },
      { name: "Joy Soap", manufacturer: "PZ Cussons" },
      { name: "Lux Soap", manufacturer: "Unilever Nigeria" },
      { name: "Macleans", manufacturer: "Haleon (GSK Consumer)" },
      { name: "MyMy" },
      { name: "Oral B", manufacturer: "Procter & Gamble" },
      { name: "Pears Soap", manufacturer: "Unilever Nigeria" },
      { name: "Premier Cool Soap" },
      { name: "Rexona", manufacturer: "Unilever Nigeria" },
      // Household cleaning
      { name: "Air Wick", manufacturer: "Reckitt Benckiser" },
      { name: "Ariel Detergent", manufacturer: "Procter & Gamble" },
      { name: "Harpic", manufacturer: "Reckitt Benckiser" },
      { name: "Hypo Bleach" },
      { name: "Jik", manufacturer: "Reckitt Benckiser" },
      { name: "Morning Fresh", manufacturer: "PZ Cussons" },
      { name: "Omo", manufacturer: "Unilever Nigeria" },
      { name: "Sunlight Detergent", manufacturer: "Unilever Nigeria" },
      { name: "Venus", manufacturer: "PZ Cussons" },
      // Sexual wellness
      { name: "Fiesta" },
      { name: "Rough Rider" },
      // Recharge / airtime
      { name: "Recharge Card MTN" },
      { name: "Recharge Card Airtel" },
      { name: "Recharge Card Glo" },
      { name: "Recharge Card 9mobile" },
    ],
    generics: [],
    strengths: [
      "Economy",
      "Family Pack",
      "Jumbo",
      "Large",
      "Medium",
      "Sachet",
      "Small",
      "33cl",
      "35cl",
      "50cl",
      "60cl",
      "75cl",
      "1L",
      "1.5L",
      "2L",
      "5L",
      "20L",
      "25g",
      "70g",
      "120g",
      "150g",
      "200g",
      "400g",
      "450g",
      "500g",
      "900g",
      "1kg",
      "2kg",
      "5kg",
      "10kg",
      "25kg",
      "50kg",
    ],
    categories: [
      "Baby Products",
      "Beer & Malt",
      "Beverages",
      "Cereals",
      "Cleaning Agents",
      "Confectionery",
      "Dairy",
      "Detergents",
      "Food & Spices",
      "Grains & Pasta",
      "Groceries",
      "Household",
      "Kitchenware",
      "Laundry",
      "Noodles",
      "Oils & Fats",
      "Personal Care",
      "Recharge Cards & Airtime",
      "Sanitary Products",
      "Snacks",
      "Soft Drinks",
      "Stationery",
      "Toiletries",
      "Water",
    ],
    dosageForms: [],
    manufacturers: [
      "BUA Group",
      "Beloxxi Industries",
      "British American Tobacco Nigeria",
      "Cadbury Nigeria",
      "Chi Limited",
      "Coca-Cola Hellenic",
      "Dangote Group",
      "Dansa Foods",
      "Dufil Prima Foods",
      "Flour Mills of Nigeria",
      "Grand Cereals",
      "Guinness Nigeria",
      "Honeywell Flour Mills",
      "International Breweries",
      "Multipro Consumer",
      "Nasco Group",
      "Nestle Nigeria",
      "Nigerian Breweries",
      "Ok Foods",
      "Promasidor",
      "PZ Cussons",
      "Rite Foods",
      "Seven-Up Bottling Company",
      "TGI Group",
      "Tolaram Group",
      "UAC Foods",
      "Unilever Nigeria",
      "Vital Products",
      "Yale Foods",
    ],
  },
  common: {
    units: [
      "Ampoule",
      "Bag",
      "Bottle",
      "Box",
      "Bundle",
      "Can",
      "Caplet",
      "Capsule",
      "Card",
      "Carton",
      "Crate",
      "Cup",
      "Dozen",
      "Drum",
      "Jar",
      "Pack",
      "Piece",
      "Roll",
      "Sachet",
      "Set",
      "Spoonful",
      "Tablet",
      "Tin",
      "Tray",
      "Tube",
      "Vial",
    ],
    locations: [
      "Aba",
      "Abakaliki",
      "Abeokuta",
      "Abiriba",
      "Abor",
      "Abraka",
      "Abuja",
      "Ado-Ekiti",
      "Afikpo",
      "Agbani",
      "Agbogugu",
      "Aguleri",
      "Ahoada",
      "Akure",
      "Amasiri",
      "Anara",
      "Arochukwu",
      "Asaba",
      "Atani",
      "Awgu",
      "Awka",
      "Azare",
      "Bali",
      "Bama",
      "Bauchi",
      "Bende",
      "Benin City",
      "Bida",
      "Birnin Kebbi",
      "Biu",
      "Bonny",
      "Buguma",
      "Bukuru",
      "Calabar",
      "Damaturu",
      "Dutse",
      "Edda",
      "Effurun",
      "Egbeda",
      "Ejigbo",
      "Ekwulobia",
      "Emene",
      "Enugu",
      "Epe",
      "Eket",
      "Gashua",
      "Gboko",
      "Gombe",
      "Gusau",
      "Gwagwalada",
      "Ibadan",
      "Igboukwu",
      "Ihiala",
      "Ijebu-Ode",
      "Ikeja",
      "Ikirun",
      "Ikom",
      "Ikorodu",
      "Ikwo",
      "Ikwuano",
      "Ilesa",
      "Ilorin",
      "Ishiagu",
      "Iseyin",
      "Isolo",
      "Iwo",
      "Jalingo",
      "Jos",
      "Kaduna",
      "Kano",
      "Katsina",
      "Keffi",
      "Lafia",
      "Lagos",
      "Lokoja",
      "Maiduguri",
      "Makurdi",
      "Mbaise",
      "Minna",
      "Mubi",
      "Nkalagu",
      "Nkpor",
      "Nnewi",
      "Nsukka",
      "Numan",
      "Obosi",
      "Ogbomoso",
      "Ogidi",
      "Oguta",
      "Ohafia",
      "Oji",
      "Oji River",
      "Okene",
      "Okigwe",
      "Oko",
      "Okposi",
      "Omoba",
      "Onitsha",
      "Onueke",
      "Opobo",
      "Oraifite",
      "Orlu",
      "Oron",
      "Osogbo",
      "Otukpo",
      "Owerri",
      "Owo",
      "Oyo",
      "Ozubulu",
      "Port Harcourt",
      "Potiskum",
      "Sagamu",
      "Sapele",
      "Shagamu",
      "Shaki",
      "Shendam",
      "Sokoto",
      "Suleja",
      "Uburu",
      "Udi",
      "Ugep",
      "Ughelli",
      "Umuahia",
      "Umuleri",
      "Umunze",
      "Umuoji",
      "Uromi",
      "Uyo",
      "Wamba",
      "Warri",
      "Yenagoa",
      "Yola",
      "Zaria",
      "Zuru",
    ],
    states: [
      "Abia State",
      "Adamawa State",
      "Akwa Ibom State",
      "Anambra State",
      "Bauchi State",
      "Bayelsa State",
      "Benue State",
      "Borno State",
      "Cross River State",
      "Delta State",
      "Ebonyi State",
      "Edo State",
      "Ekiti State",
      "Enugu State",
      "FCT - Abuja",
      "Gombe State",
      "Imo State",
      "Jigawa State",
      "Kaduna State",
      "Kano State",
      "Katsina State",
      "Kebbi State",
      "Kogi State",
      "Kwara State",
      "Lagos State",
      "Nasarawa State",
      "Niger State",
      "Ogun State",
      "Ondo State",
      "Osun State",
      "Oyo State",
      "Plateau State",
      "Rivers State",
      "Sokoto State",
      "Taraba State",
      "Yobe State",
      "Zamfara State",
    ],
  },
};

export const NIGERIAN_BANKS = [
  "Access Bank",
  "ALAT by WEMA",
  "Baobab Microfinance Bank",
  "Carbon",
  "Citibank Nigeria",
  "Coronation Merchant Bank",
  "Ecobank Nigeria",
  "Eyowo",
  "FairMoney",
  "Fidelity Bank",
  "Fina Trust Microfinance Bank",
  "First Bank of Nigeria",
  "First City Monument Bank (FCMB)",
  "FSDH Merchant Bank",
  "Globus Bank",
  "Guaranty Trust Bank (GTB)",
  "Jaiz Bank",
  "Keystone Bank",
  "Kuda Bank",
  "LAPO Microfinance Bank",
  "Lotus Bank",
  "Mint (formerly Mint-FSDH)",
  "Moniepoint",
  "Nova Merchant Bank",
  "Opay",
  "Optimus Bank",
  "Palmpay",
  "Parallex Bank",
  "Paga",
  "Pocket App",
  "Polaris Bank",
  "PremiumTrust Bank",
  "Providus Bank",
  "PiggyVest",
  "Rand Merchant Bank",
  "Renmoney",
  "Rubies Bank",
  "Signature Bank",
  "Sparkle",
  "Stanbic IBTC Bank",
  "Standard Chartered Bank",
  "Sterling Bank",
  "SunTrust Bank",
  "TAJBank",
  "Titan Trust Bank",
  "Union Bank of Nigeria",
  "United Bank for Africa (UBA)",
  "Unity Bank",
  "VFD Microfinance Bank",
  "Wema Bank",
  "Zenith Bank",
];
