CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" varchar, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE TABLE IF NOT EXISTS "roles" ("id" integer primary key autoincrement not null, "name" varchar not null, "slug" varchar not null, "description" text, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "roles_slug_unique" on "roles" ("slug");
CREATE TABLE IF NOT EXISTS "permissions" ("id" integer primary key autoincrement not null, "name" varchar not null, "slug" varchar not null, "description" text, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "permissions_slug_unique" on "permissions" ("slug");
CREATE TABLE IF NOT EXISTS "permission_role" ("id" integer primary key autoincrement not null, "role_id" integer not null, "permission_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("role_id") references "roles"("id") on delete cascade, foreign key("permission_id") references "permissions"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "activity_logs" ("id" integer primary key autoincrement not null, "user_id" varchar not null, "action" varchar not null, "description" varchar, "ip_address" varchar, "user_agent" varchar, "properties" text, "created_at" datetime, "updated_at" datetime, "_synced_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_id" varchar not null, "tokenable_type" varchar not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime, ip_address VARCHAR(45) NULL, user_agent TEXT NULL);
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE TABLE IF NOT EXISTS "prescription_items" ("id" varchar not null, "prescription_id" varchar not null, "product_id" varchar not null, "dosage" varchar, "quantity_prescribed" integer not null, "quantity_dispensed" integer not null default '0', "status" varchar check ("status" in ('pending', 'dispensed', 'substituted', 'unavailable')) not null default 'pending', "refills_authorized" integer default '0', "refills_used" integer default '0', "refill_interval_days" integer default '30', "next_refill_date" date, "created_at" datetime, "updated_at" datetime, foreign key("prescription_id") references "prescriptions"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade, primary key ("id"));
CREATE TABLE IF NOT EXISTS "stock_movements" ("id" varchar not null, "stock_batch_id" varchar not null, "product_id" varchar not null, "movement_type" varchar check ("movement_type" in ('purchase', 'sale', 'adjustment', 'transfer', 'return', 'expired', 'damaged')) not null, "quantity" integer not null, "unit_cost" numeric, "total_cost" numeric, "reference_id" varchar, "reference_type" varchar, "reason" text, "performed_by" varchar not null, "movement_date" datetime not null default CURRENT_TIMESTAMP, "created_at" datetime, "updated_at" datetime, "_synced_at" datetime, foreign key("stock_batch_id") references "stock_batches"("id"), foreign key("product_id") references "products"("id"), foreign key("performed_by") references "users"("id"), primary key ("id"));
CREATE TABLE IF NOT EXISTS "purchase_orders" ("id" varchar not null, "order_number" varchar not null, "supplier_id" varchar not null, "ordered_by" varchar not null, "status" varchar check ("status" in ('pending', 'approved', 'ordered', 'received', 'cancelled')) not null default 'pending', "order_date" date not null, "expected_delivery_date" date, "actual_delivery_date" date, "subtotal" numeric not null default '0', "tax_amount" numeric not null default '0', "total_amount" numeric not null default '0', "notes" text, "created_at" datetime, "updated_at" datetime, "_synced_at" datetime, foreign key("supplier_id") references "suppliers"("id"), foreign key("ordered_by") references "users"("id"), primary key ("id"));
CREATE UNIQUE INDEX "purchase_orders_order_number_unique" on "purchase_orders" ("order_number");
CREATE TABLE IF NOT EXISTS "purchase_order_items" ("id" varchar not null, "purchase_order_id" varchar not null, "product_id" varchar not null, "quantity_ordered" integer not null, "quantity_received" integer not null default '0', "unit_cost" numeric not null, "total_cost" numeric not null, "batch_number" varchar, "expiry_date" date, "status" varchar check ("status" in ('pending', 'received', 'partial', 'cancelled')) not null default 'pending', "created_at" datetime, "updated_at" datetime, "_synced_at" datetime, foreign key("purchase_order_id") references "purchase_orders"("id") on delete cascade, foreign key("product_id") references "products"("id"), primary key ("id"));
CREATE TABLE IF NOT EXISTS "licenses" ("id" varchar not null, "subscription_id" varchar not null, "machine_id" varchar not null, "machine_name" varchar, "last_check_in" datetime, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, foreign key("subscription_id") references "subscriptions"("id") on delete cascade, primary key ("id"));
CREATE UNIQUE INDEX "licenses_subscription_id_machine_id_unique" on "licenses" ("subscription_id", "machine_id");
CREATE TABLE IF NOT EXISTS "backups" ("id" varchar not null, "filename" text not null, "size" integer not null, "hash" varchar not null, "created_by" varchar not null, "restored_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("created_by") references "users"("id"), primary key ("id"));
CREATE TABLE IF NOT EXISTS "sales" ("id" varchar not null, "transaction_number" varchar not null, "customer_id" varchar, "cashier_id" varchar not null, "prescription_id" varchar, "subtotal" numeric not null default ('0'), "discount_amount" numeric not null default ('0'), "discount_percentage" numeric not null default ('0'), "tax_amount" numeric not null default ('0'), "tax_percentage" numeric not null default ('7.5'), "total_amount" numeric not null, "payment_method" varchar not null, "payment_status" varchar not null default ('completed'), "amount_paid" numeric not null, "change_given" numeric not null default ('0'), "points_earned" integer not null default ('0'), "points_redeemed" integer not null default ('0'), "transaction_date" datetime not null default (CURRENT_TIMESTAMP), "notes" text, "receipt_printed" tinyint(1) not null default ('0'), "created_at" datetime, "updated_at" datetime, "_synced_at" datetime, "deleted_at" datetime, "user_id" varchar, foreign key("prescription_id") references prescriptions("id") on delete set null on update no action, foreign key("cashier_id") references users("id") on delete no action on update no action, foreign key("customer_id") references customers("id") on delete set null on update no action, foreign key("user_id") references "users"("id") on delete cascade, primary key ("id"));
CREATE INDEX "sales__synced_at_index" on "sales" ("_synced_at");
CREATE UNIQUE INDEX "sales_transaction_number_unique" on "sales" ("transaction_number");
CREATE TABLE IF NOT EXISTS "customers" ("id" varchar not null, "first_name" varchar not null, "last_name" varchar not null, "email" varchar, "phone" varchar, "address" text, "date_of_birth" date, "gender" varchar, "allergies" text, "medical_conditions" text, "loyalty_points" integer not null default ('0'), "created_at" datetime, "updated_at" datetime, "_synced_at" datetime, "deleted_at" datetime, "user_id" varchar, foreign key("user_id") references "users"("id") on delete cascade, primary key ("id"));
CREATE INDEX "customers__synced_at_index" on "customers" ("_synced_at");
CREATE TABLE IF NOT EXISTS "products" ("id" varchar not null, "name" varchar not null, "generic_name" varchar, "brand_name" varchar, "category_id" varchar, "manufacturer" varchar, "supplier_id" varchar, "nafdac_number" varchar, "dosage_form" varchar, "strength" varchar, "pack_size" integer not null default ('1'), "unit_of_measure" varchar not null default ('piece'), "description" text, "indications" text, "contraindications" text, "side_effects" text, "storage_conditions" text, "requires_prescription" tinyint(1) not null default ('0'), "is_controlled" tinyint(1) not null default ('0'), "is_active" tinyint(1) not null default ('1'), "cost_price" numeric not null default ('0'), "selling_price" numeric not null default ('0'), "markup_percentage" numeric not null default ('0'), "barcode" varchar, "created_at" datetime, "updated_at" datetime, "_synced_at" datetime, "deleted_at" datetime, "user_id" varchar, foreign key("supplier_id") references suppliers("id") on delete set null on update no action, foreign key("category_id") references categories("id") on delete set null on update no action, foreign key("user_id") references "users"("id") on delete cascade, primary key ("id"));
CREATE INDEX "products__synced_at_index" on "products" ("_synced_at");
CREATE INDEX "products_barcode_index" on "products" ("barcode");
CREATE TABLE IF NOT EXISTS "stock_batches" ("id" varchar not null, "product_id" varchar not null, "batch_number" varchar not null, "quantity_in_stock" integer not null default ('0'), "quantity_reserved" integer not null default ('0'), "reorder_level" integer not null default ('10'), "max_stock_level" integer not null default ('1000'), "cost_price" numeric not null, "selling_price" numeric not null, "manufacture_date" date, "expiry_date" date not null, "supplier_id" varchar, "location" varchar, "status" varchar not null default ('active'), "created_at" datetime, "updated_at" datetime, "user_id" varchar, "_synced_at" datetime, foreign key("supplier_id") references suppliers("id") on delete set null on update no action, foreign key("product_id") references products("id") on delete cascade on update no action, foreign key("user_id") references "users"("id") on delete cascade, primary key ("id"));
CREATE INDEX "stock_batch_expiry_date_index" on "stock_batches" ("expiry_date");
CREATE UNIQUE INDEX "stock_batch_product_id_batch_number_unique" on "stock_batches" ("product_id", "batch_number");
CREATE TABLE IF NOT EXISTS "subscriptions" ("id" varchar not null, "user_id" varchar not null, "plan_name" varchar not null, "start_date" datetime not null, "end_date" datetime not null, "status" varchar not null default 'active', "license_key" varchar not null, "created_at" datetime, "updated_at" datetime, "is_trial" tinyint(1) not null default 0, foreign key("user_id") references "users"("id") on delete cascade, primary key ("id"));
CREATE UNIQUE INDEX "subscriptions_license_key_unique" on "subscriptions" ("license_key");
CREATE TABLE IF NOT EXISTS "payment_transactions" ("id" varchar not null, "subscription_id" varchar, "provider" varchar not null, "provider_reference" varchar not null, "amount" numeric not null, "currency" varchar not null default ('NGN'), "status" varchar not null, "metadata" text, "created_at" datetime, "updated_at" datetime, "user_id" varchar, foreign key("subscription_id") references subscriptions("id") on delete no action on update no action, foreign key("user_id") references "users"("id") on delete cascade, primary key ("id"));
CREATE UNIQUE INDEX "payment_transactions_provider_reference_unique" on "payment_transactions" ("provider_reference");
CREATE TABLE IF NOT EXISTS "categories" ("id" varchar not null, "name" varchar not null, "description" text, "parent_id" varchar, "is_active" tinyint(1) not null default ('1'), "created_at" datetime, "updated_at" datetime, "user_id" varchar, "_synced_at" datetime, foreign key("parent_id") references categories("id") on delete set null on update no action, foreign key("user_id") references "users"("id") on delete cascade, primary key ("id"));
CREATE UNIQUE INDEX "categories_name_unique" on "categories" ("name");
CREATE TABLE IF NOT EXISTS "suppliers" ("id" varchar not null, "name" varchar not null, "contact_person" varchar, "email" varchar, "phone" varchar, "address" text, "city" varchar, "state" varchar, "country" varchar not null default ('Nigeria'), "tax_id" varchar, "payment_terms" integer not null default ('30'), "is_active" tinyint(1) not null default ('1'), "rating" numeric not null default ('0'), "created_at" datetime, "updated_at" datetime, "_synced_at" datetime, "deleted_at" datetime, "user_id" varchar, foreign key("user_id") references "users"("id") on delete cascade, primary key ("id"));
CREATE INDEX "suppliers__synced_at_index" on "suppliers" ("_synced_at");
CREATE TABLE IF NOT EXISTS "prescriptions" ("id" varchar not null, "prescription_number" varchar not null, "customer_id" varchar, "doctor_name" varchar, "hospital_name" varchar, "prescription_date" date not null, "diagnosis" text, "notes" text, "status" varchar not null default ('pending'), "substituted_product_id" varchar, "substitution_reason" text, "created_at" datetime, "updated_at" datetime, "user_id" varchar, foreign key("substituted_product_id") references products("id") on delete set null on update no action, foreign key("customer_id") references customers("id") on delete set null on update no action, foreign key("user_id") references "users"("id") on delete cascade, primary key ("id"));
CREATE UNIQUE INDEX "prescriptions_prescription_number_unique" on "prescriptions" ("prescription_number");
CREATE TABLE feedback (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NULL,
    type VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    contact_email VARCHAR(255) NULL,
    status VARCHAR(255) DEFAULT 'pending',
    _deleted TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
, "_synced_at" datetime);
CREATE TABLE IF NOT EXISTS "stores" ("id" varchar not null, "user_id" varchar not null, "name" varchar not null, "location" varchar, "device_id" varchar not null, "last_sync_at" datetime, "created_at" datetime, "updated_at" datetime, "store_type" varchar not null default 'pharmacy', "address" varchar, "phone" varchar, "email" varchar, "currency" varchar not null default 'NGN', "vat_percentage" numeric not null default '7.5', "pcn_license" varchar, "receipt_header" text, "receipt_footer" text, "show_logo_on_receipt" tinyint(1) not null default '1', "show_contact_on_receipt" tinyint(1) not null default '1', "low_stock_warning" tinyint(1) not null default '1', "expiry_warning" tinyint(1) not null default '1', "expiry_warning_days" integer not null default '90', "_version" integer not null default '1', "_synced_at" datetime, "auto_sync_enabled" tinyint(1) not null default '0', "auto_sync_interval" integer not null default '15', "status" varchar not null default 'Active', "suspension_reason" text, "show_retail_suggestions" tinyint(1) not null default '0', foreign key("user_id") references users("id") on delete cascade on update no action, foreign key("user_id") references "users"("id") on delete cascade, primary key ("id"));
CREATE UNIQUE INDEX "stores_device_id_unique" on "stores" ("device_id");
CREATE TABLE IF NOT EXISTS "notifications" ("id" varchar not null, "user_id" varchar not null, "title" varchar not null, "message" text not null, "type" varchar not null default 'info', "is_read" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, primary key ("id"));
CREATE TABLE IF NOT EXISTS "users" ("id" varchar not null, "email" varchar not null, "password" varchar not null, "first_name" varchar not null, "last_name" varchar not null, "phone" varchar, "role" varchar not null default ('pharmacist'), "is_active" tinyint(1) not null default ('1'), "last_login_at" datetime, "remember_token" varchar, "created_at" datetime, "updated_at" datetime, "role_id" integer, "_synced_at" datetime, "deleted_at" datetime, "username" varchar, "pin" varchar, "store_id" varchar, "deletion_requested_at" datetime, "deletion_reason" text, "setup_reminder_level" integer not null default '0', "setup_reminder_last_sent_at" datetime, foreign key("role_id") references roles("id") on delete set null on update no action, foreign key("store_id") references "stores"("id") on delete set null, primary key ("id"));
CREATE INDEX "users__synced_at_index" on "users" ("_synced_at");
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE UNIQUE INDEX "users_username_unique" on "users" ("username");
CREATE TABLE IF NOT EXISTS "broadcasts" ("id" varchar not null, "title" varchar not null, "message" text not null, "type" varchar not null default 'info', "is_active" tinyint(1) not null default '1', "target_type" varchar not null default 'all', "expires_at" datetime, "created_at" datetime, "updated_at" datetime, "user_ids" text, primary key ("id"));
CREATE TABLE IF NOT EXISTS "permission_user" ("id" integer primary key autoincrement not null, "user_id" varchar not null, "permission_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, foreign key("permission_id") references "permissions"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE TABLE IF NOT EXISTS "email_templates" ("id" integer primary key autoincrement not null, "key" varchar not null, "name" varchar not null, "subject" varchar not null, "content" text not null, "variables" text not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "email_templates_key_unique" on "email_templates" ("key");
CREATE TABLE IF NOT EXISTS "vendors" ("id" varchar not null, "user_id" varchar, "name" varchar not null, "contact_person" varchar, "email" varchar, "phone" varchar, "address" varchar, "tax_id" varchar, "payment_terms" varchar, "rating" numeric not null default '0', "is_active" tinyint(1) not null default '1', "_version" integer not null default '1', "_synced" tinyint(1) not null default '0', "_synced_at" datetime, "deleted_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE INDEX "vendors_user_id_index" on "vendors" ("user_id");
CREATE TABLE IF NOT EXISTS "expenses" ("id" varchar not null, "user_id" varchar, "category" varchar not null, "description" text, "amount" numeric not null, "date" varchar not null, "payment_method" varchar, "vendor_name" varchar, "reference_number" varchar, "_version" integer not null default '1', "_synced" tinyint(1) not null default '0', "_synced_at" datetime, "deleted_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE INDEX "expenses_user_id_index" on "expenses" ("user_id");
CREATE TABLE IF NOT EXISTS "system_configs" ("id" integer primary key autoincrement not null, "key" varchar not null, "value" text not null, "description" varchar, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "system_configs_key_unique" on "system_configs" ("key");
CREATE INDEX "stock_batch__synced_at_index" on "stock_batches" ("_synced_at");
CREATE INDEX "activity_logs__synced_at_index" on "activity_logs" ("_synced_at");
CREATE INDEX "categories__synced_at_index" on "categories" ("_synced_at");
CREATE INDEX "products_updated_at_index" on "products" ("updated_at");
CREATE INDEX "customers_updated_at_index" on "customers" ("updated_at");
CREATE INDEX "suppliers_updated_at_index" on "suppliers" ("updated_at");
CREATE INDEX "sales_updated_at_index" on "sales" ("updated_at");
CREATE INDEX "users_updated_at_index" on "users" ("updated_at");
CREATE INDEX "stock_batch_updated_at_index" on "stock_batches" ("updated_at");
CREATE INDEX "activity_logs_updated_at_index" on "activity_logs" ("updated_at");
CREATE INDEX "categories_updated_at_index" on "categories" ("updated_at");
CREATE TABLE IF NOT EXISTS "sale_items" ("id" varchar not null, "sale_id" varchar not null, "product_id" varchar not null, "stock_batch_id" varchar, "quantity" integer not null, "unit_price" numeric not null, "discount_amount" numeric not null default ('0'), "total_price" numeric not null, "cost_price" numeric, "created_at" datetime, "updated_at" datetime, "_synced_at" datetime, "deleted_at" datetime, foreign key("sale_id") references sales("id") on delete cascade on update no action, foreign key("product_id") references products("id") on delete no action on update no action, foreign key("stock_batch_id") references stock_batches("id") on delete no action on update no action, primary key ("id"));
CREATE INDEX "sale_items__synced_at_index" on "sale_items" ("_synced_at");
CREATE INDEX "sale_items_updated_at_index" on "sale_items" ("updated_at");
CREATE INDEX "stock_movements__synced_at_index" on "stock_movements" ("_synced_at");
CREATE INDEX "purchase_orders__synced_at_index" on "purchase_orders" ("_synced_at");
CREATE INDEX "purchase_order_items__synced_at_index" on "purchase_order_items" ("_synced_at");
CREATE INDEX "feedback__synced_at_index" on "feedback" ("_synced_at");
