name: Deploy Laravel Backend

on:
  push:
    branches:
      - main
    paths:
      - "laravel-server/**"
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup PHP
        uses: shivammathur/setup-php@a4e22b60bbb9c1021113f2860347b0759f66fe5d # v2.30.0
        with:
          php-version: "8.2"
          extensions: mbstring, intl, pdo, pdo_mysql

      - name: 📁 Setup Directory Structure
        run: |
          cd laravel-server
          mkdir -p bootstrap/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p storage/framework/cache
          chmod -R 777 storage bootstrap/cache

      - name: 📦 Install Dependencies
        run: |
          cd laravel-server
          composer install --no-dev --optimize-autoloader

      - name: 📖 Generate API docs
        run: |
          cd laravel-server
          php artisan l5-swagger:generate

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@8e83cea8672e3fbcbb9fdafff34debf6ae4c5f65 # v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /api.dumosrx.com/
          local-dir: ./laravel-server/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            **/storage/*.key
            .env.example
            .env


